; Cries indexes (see audio/cry_pointers.asm)
	const_def

; gen 1
	const CRY_NIDORAN_M
	const CRY_NIDORAN_F
	const CRY_SLOWPOKE
	const CRY_KANGASKHAN
	const CRY_CHARMANDER
	const CRY_GRIMER
	const CRY_VOLTORB
	const CRY_MUK
	const CRY_ODDISH
	const CRY_RAICHU
	const CRY_NIDOQUEEN
	const CRY_DIGLETT
	const CRY_SEEL
	const CRY_DROWZEE
	const CRY_PIDGEY
	const CRY_BULBASAUR
	const CRY_SPEAROW
	const CRY_RHYDON
	const CRY_GOLEM
	const CRY_BLASTOISE
	const CRY_PIDGEOTTO
	const CRY_WEEDLE
	const CRY_CATERPIE
	const CRY_EKANS
	const CRY_FEAROW
	const CRY_CLEFAIRY
	const CRY_VENONAT
	const CRY_LAPRAS
	const CRY_METAPOD
	const CRY_SQUIRTLE
	const CRY_PARAS
	const CRY_GROWLITHE
	const CRY_KRABBY
	const CRY_PSYDUCK
	const CRY_RATTATA
	const CRY_VILEPLUME
	const CRY_VULPIX
	const CRY_WEEPINBELL

; gen 2
	const CRY_MARILL
	const CRY_SPINARAK
	const CRY_TOGEPI
	const CRY_GIRAFARIG
	const CRY_RAIKOU
	const CRY_MAREEP
	const CRY_TOGETIC
	const CRY_HOOTHOOT
	const CRY_SENTRET
	const CRY_SLOWKING
	const CRY_CYNDAQUIL
	const CRY_CHIKORITA
	const CRY_TOTODILE
	const CRY_GLIGAR
	const CRY_CLEFFA
	const CRY_SLUGMA
	const CRY_LEDYBA
	const CRY_ENTEI
	const CRY_WOOPER
	const CRY_MANTINE
	const CRY_TYPHLOSION
	const CRY_NATU
	const CRY_TEDDIURSA
	const CRY_SUNFLORA
	const CRY_AMPHAROS
	const CRY_MAGCARGO
	const CRY_PICHU
	const CRY_AIPOM
	const CRY_DUNSPARCE
	const CRY_DONPHAN
	const CRY_HYDREIGON
	const CRY_ZYGARDE
	const CRY_STOUTLAND
	const CRY_EMPOLEON
	const CRY_MAGNEZONE
    const CRY_PATRAT ;BW3
	const CRY_MEDITITE ;BW3
	const CRY_YAMASK ;BW3
	const CRY_WHIMSICOTT ;BW3
	const CRY_KARRABLAST ;BW3
	const CRY_SHELMET ;BW3
	const CRY_TIRTOUGA ;BW3
	const CRY_MUDKIP ;BW3
	const CRY_CERULEDGE ;BW3
	const CRY_SWAMPERT ;BW3
	const CRY_CHARJABUG ;BW3
	const CRY_VIKAVOLT ;BW3
	const CRY_CORVIKNIGHT ;BW3
	const CRY_GOROCHU ;The unused one
	const CRY_SHROOMISH
	const CRY_BRELOOM
	const CRY_RALTS
	const CRY_KIRLIA
	const CRY_GALLADE
	const CRY_SNEASLER
	const CRY_DRILBUR
	const CRY_EXCADRILL
	const CRY_HOOTHOOT_2CH
	const CRY_WORFURS
	const CRY_MOLAMBINO
	const CRY_MISDREAVUS
	const CRY_YANMA
	const CRY_ELEKID
	const CRY_LARVITAR
	const CRY_BIPULLA
	const CRY_AGGROSWINE
	const CRY_TRICULES
	const CRY_ARON
	const CRY_LAIRON
	const CRY_AGGRON
	const CRY_SWABLU
	const CRY_ALTARIA
	const CRY_SYLVEON
	const CRY_AMAURA
	const CRY_CHATOT
	const CRY_VENIPEDE
	const CRY_LEAFEON
	const CRY_GLITCHED
	const CRY_UMBREON_RED
	const CRY_LARVESTA
	const CRY_GOLURK
	const CRY_KOTORA
	const CRY_ANCHORAGE
	const CRY_GROTESS
	const CRY_DISTURBAN
	const CRY_STAKATAKA
	const CRY_NECROZMA
DEF NUM_CRIES EQU const_value
