MACRO command
	const \1_command
	DEF \1 EQUS "db \1_command"
ENDM

; BattleCommandPointers indexes (see data/battle/effect_command_pointers.asm)
	const_def 1
	command checkturn               ; 01
	command checkobedience          ; 02
	command usedmovetext            ; 03
	command doturn                  ; 04
	command critical                ; 05
	command damagestats             ; 06
	command stab                    ; 07
	command damagevariation         ; 08
	command checkhit                ; 09
	command lowersub                ; 0a
	command moveanimnosub           ; 0b
	command raisesub                ; 0c
	command failuretext             ; 0d
	command applydamage             ; 0e
	command criticaltext            ; 0f
	command supereffectivetext      ; 10
	command checkfaint              ; 11
	command buildopponentrage       ; 12
	command poisontarget            ; 13
	command sleeptarget             ; 14
	command draintarget             ; 15
	command eatdream                ; 16
	command burntarget              ; 17
	command freezetarget            ; 18
	command paralyzetarget          ; 19
	command selfdestruct            ; 1a
	command strengthsap             ; 1b
	command statup                  ; 1c
	command statdown                ; 1d
	command payday                  ; 1e
	command conversion              ; 1f
	command resetstats              ; 20
	command forceswitch             ; 21
	command endloop                 ; 22
	command flinchtarget            ; 23
	command ohko                    ; 24
	command recoil                  ; 25
	command mist                    ; 26
	command focusenergy             ; 27
	command confuse                 ; 28
	command confusetarget           ; 29
	command heal                    ; 2a
	command transform               ; 2b
	command screen                  ; 2c
	command poison                  ; 2d
	command paralyze                ; 2e
	command substitute              ; 2f
	command rechargenextturn        ; 30
	command metronome               ; 31
	command leechseed               ; 32
	command splash                  ; 33
	command disable                 ; 34
	command cleartext               ; 35
	command charge                  ; 36
	command checkcharge             ; 37
	command traptarget              ; 38
	command rampage                 ; 39
	command checkrampage            ; 3a
	command constantdamage          ; 3b
	command counter                 ; 3c
	command encore                  ; 3d
	command painsplit               ; 3e
	command snore                   ; 3f
	command conversion2             ; 40
	command lockon                  ; 41
	command sketch                  ; 42
	command defrostopponent         ; 43
	command sleeptalk               ; 44
	command destinybond             ; 45
	command spite                   ; 46
	command falseswipe              ; 47
	command healbell                ; 48
	command kingsrock               ; 49
	command thief                   ; 4c
	command arenatrap               ; 4d
	command defrost                 ; 4f
	command curse                   ; 50
	command protect                 ; 51
	command spikes                  ; 52
	command perishsong              ; 54
	command startsandstorm          ; 55
	command endure                  ; 56
	command checkrollout            ; 57
	command rolloutpower            ; 58
	command furycutter              ; 59
	command attract                 ; 5a
	command happinesspower          ; 5b
	command damagecalc              ; 5c
	command safeguard               ; 5e
	command checksafeguard          ; 5f
	command batonpass               ; 60
	command pursuit                 ; 61
	command clearhazards            ; 62
	command healmorn                ; 63
	command healday                 ; 64
	command healnite                ; 65
	command hiddenpower             ; 66
	command startrain               ; 67
	command startsun                ; 68
	command attackup                ; 69
	command defenseup               ; 6a
	command speedup                 ; 6b
	command specialattackup         ; 6c
	command specialdefenseup        ; 6d
	command accuracyup              ; 6e
	command evasionup               ; 6f
	command attackup2               ; 70
	command defenseup2              ; 71
	command speedup2                ; 72
	command specialattackup2        ; 73
	command specialdefenseup2       ; 74
	command accuracyup2             ; 75
	command evasionup2              ; 76
	command attackdown              ; 77
	command defensedown             ; 78
	command speeddown               ; 79
	command specialattackdown       ; 7a
	command specialdefensedown      ; 7b
	command accuracydown            ; 7c
	command evasiondown             ; 7d
	command attackdown2             ; 7e
	command defensedown2            ; 7f
	command speeddown2              ; 80
	command specialattackdown2      ; 81
	command specialdefensedown2     ; 82
	command accuracydown2           ; 83
	command evasiondown2            ; 84
	command statupmessage           ; 85
	command statdownmessage         ; 86
	command statupfailtext          ; 87
	command statdownfailtext        ; 88
	command effectchance            ; 89
	command statdownanim            ; 8a
	command statupanim              ; 8b
	command switchturn              ; 8c
	command fakeout                 ; 8d
	command bellydrum               ; 8e
	command rage                    ; 90
	command doubleflyingdamage      ; 91
	command doubleundergrounddamage ; 92
	command mirrorcoat              ; 93
	command checkfuturesight        ; 94
	command futuresight             ; 95
	command doubleminimizedamage    ; 96
	command skipsuncharge           ; 97
	command thunderaccuracy         ; 98
	command teleport                ; 99
	command ragedamage              ; 9a
	command resettypematchup        ; 9b
	command allstatsup              ; 9c
	command raisesubnoanim          ; 9d
	command lowersubnoanim          ; 9e
	command clearmissdamage         ; 9f
	command movedelay               ; a0
	command moveanim                ; a1
	command tristatuschance         ; a2
	command supereffectivelooptext  ; a3
	command startloop               ; a4
	command curl                    ; a5
	command armorcannon 			; a6
	command calmmind 				; a7
	command thunderclap 			; a8
	command traphit 				; a9
	command bulkup 					; aa
	command overheat 				; ab
	command beatup 					; ac
	command quiverdance 			; ad
	command victorydance 			; ae
	command burn 					; af
DEF NUM_EFFECT_COMMANDS EQU const_value - 1

	const_def -1, -1
	command endmove                 ; ff
	command endturn                 ; fe
