Cries:
; entries correspond to CRY_* constants (see constants/cry_constants.asm)
	table_width 3
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Slowpoke
	dba Cry_Kangaskhan
	dba Cry_Charmander
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Muk
	dba Cry_Oddish
	dba Cry_Raichu
	dba Cry_Nidoqueen
	dba Cry_Diglett
	dba Cry_Seel
	dba Cry_Drowzee
	dba Cry_Pidgey
	dba Cry_Bulbasaur
	dba Cry_Spearow
	dba Cry_Rhydon
	dba Cry_Golem
	dba Cry_Blastoise
	dba Cry_Pidgeotto
	dba Cry_Weedle
	dba Cry_Caterpie
	dba Cry_Ekans
	dba Cry_Fearow
	dba Cry_Clefairy
	dba Cry_Venonat
	dba Cry_Lapras
	dba Cry_Metapod
	dba Cry_Squirtle
	dba Cry_Paras
	dba Cry_Growlithe
	dba Cry_Krabby
	dba Cry_Psyduck
	dba Cry_Rattata
	dba Cry_Vileplume
	dba Cry_Vulpix
	dba Cry_Weepinbell
	dba Cry_Marill
	dba Cry_Spinarak
	dba Cry_Togepi
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Mareep
	dba Cry_Togetic
	dba Cry_Hoothoot
	dba Cry_Sentret
	dba Cry_Slowking
	dba Cry_Cyndaquil
	dba Cry_Chikorita
	dba Cry_Totodile
	dba Cry_Gligar
	dba Cry_Cleffa
	dba Cry_Slugma
	dba Cry_Ledyba
	dba Cry_Entei
	dba Cry_Wooper
	dba Cry_Mantine
	dba Cry_Typhlosion
	dba Cry_Natu
	dba Cry_Teddiursa
	dba Cry_Sunflora
	dba Cry_Ampharos
	dba Cry_Magcargo
	dba Cry_Pichu
	dba Cry_Aipom
	dba Cry_Dunsparce
	dba Cry_Donphan
	dba Cry_Hydreigon ;BW3G
	dba Cry_Zygarde ;Modified Cry_Hydreigon
	dba Cry_Stoutland ;BW3G
	dba Cry_Empoleon ;WIP Cry
	dba Cry_Magnezone ;BW3G
	dba Cry_Patrat
	dba Cry_Meditite
	dba Cry_Yamask
	dba Cry_Whimsicott
	dba Cry_Karrablast
	dba Cry_Shelmet
	dba Cry_Tirtouga
	dba Cry_Mudkip
	dba Cry_Ceruledge
	dba Cry_Swampert
	dba Cry_Charjabug
	dba Cry_Vikavolt
	dba Cry_Corviknight
	dba Cry_Gorochu
	dba Cry_Shroomish
	dba Cry_Breloom
	dba Cry_Ralts
	dba Cry_Kirlia
	dba Cry_Gallade
	dba Cry_Sneasler
	dba Cry_Drilbur
	dba Cry_Excadrill
	dba Cry_Hoothoot_2ch
	dba Cry_Worfurs
	dba Cry_Molambino
	dba Cry_Misdreavus
	dba Cry_Yanma
	dba Cry_Elekid
	dba Cry_Larvitar
	dba Cry_Bipulla
	dba Cry_Aggroswine
	dba Cry_Tricules
	dba Cry_Aron
	dba Cry_Lairon
	dba Cry_Aggron
	dba Cry_Swablu
	dba Cry_Altaria
	dba Cry_Sylveon
	dba Cry_Amaura
	dba Cry_Chatot
	dba Cry_Venipede
	dba Cry_Leafeon
	dba Cry_Glitched
	dba Cry_UmbreonRed
	dba Cry_Larvesta
	dba Cry_Golurk
	dba Cry_Kotora
	dba Cry_Anchorage
	dba Cry_Grotess
	dba Cry_Disturban
	dba Cry_Stakataka
	dba Cry_Necrozma
	assert_table_length NUM_CRIES
