AnimationPointers:
	table_width 2
	dw TreeckoAnimation
	dw GrovyleAnimation
	dw SceptileAnimation
	dw TorchicAnimation
	dw CombuskenAnimation
	dw BlazikenAnimation
	dw MudkipAnimation
	dw MarshtompAnimation
	dw SwampertAnimation
	dw GrubbinAnimation
	dw CharjabugAnimation
	dw VikavoltAnimation
	dw VenipedeAnimation
	dw WhirlipedeAnimation
	dw ScolipedeAnimation
	dw RookideeAnimation
	dw CorvisquireAnimation
	dw CorviknightAnimation
	dw ZigzagoonAnimation
	dw LinooneAnimation
	dw TaillowAnimation
	dw SwellowAnimation
	dw KotoraAnimation
	dw RaitoraAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw SandygastAnimation
	dw PalossandAnimation
	dw SableyeAnimation
	dw RoseliaAnimation
	dw RoseradeAnimation
	dw CharcadetAnimation
	dw ArmarogueAnimation
	dw CeruledgeAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw GlimmetAnimation
	dw GlimmoraAnimation
	dw CutieflyAnimation
	dw RibombeeAnimation
	dw RinringAnimation
	dw BellerunAnimation
	dw GavillainAnimation
	dw CactriAnimation
	dw SharpoonAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw LarvestaAnimation
	dw VolcaronaAnimation
	dw DrilburAnimation
	dw ExcadrillAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw WimpodAnimation
	dw GolisopodAnimation
	dw PetililAnimation
	dw LilligantAnimation
	dw LilligantHisuiAnimation
	dw OrthwormAnimation
	dw MimikyuAnimation
	dw SphealAnimation
	dw SealeoAnimation
	dw WalreinAnimation
	dw HatennaAnimation
	dw HattremAnimation
	dw HattereneAnimation
	dw DedenneAnimation
	dw GolettAnimation
	dw GolurkAnimation
	dw BellsproutAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw SwavybellAnimation
	dw AronAnimation
	dw LaironAnimation
	dw AggronAnimation
	dw DarumakaAnimation
	dw DarmanitanAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw SlowkingAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw MagnezoneAnimation
	dw FarfetchDAnimation
	dw LuxwanAnimation
	dw ChatotAnimation
	dw HawluchaAnimation
	dw WailmerAnimation
	dw WailordAnimation
	dw SkrelpAnimation
	dw DragalgeAnimation
	dw ShellderAnimation
	dw CloysterAnimation
	dw TurbannAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw AbsolAnimation
	dw InkayAnimation
	dw MalamarAnimation
	dw ClauncherAnimation
	dw ClawitzerAnimation
	dw ImpidimpAnimation
	dw MorgremAnimation
	dw GrimmsnarlAnimation
	dw SpiritombAnimation
	dw CuboneAnimation
	dw MarowakAnimation
	dw LatiasAnimation
	dw LatiosAnimation
	dw LickitungAnimation
	dw LickikingAnimation
	dw VaroomAnimation
	dw RevavroomAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw RhyperiorAnimation
	dw ChanseyAnimation
	dw BlisseyAnimation
	dw TangelaAnimation
	dw TangorestAnimation
	dw BomseekerAnimation
	dw CorsasunAnimation
	dw AnchorageAnimation
	dw GrotessAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw ScytherAnimation
	dw JoltikAnimation
	dw GalvantulaAnimation
	dw PinsirAnimation
	dw PraxeAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw FalinksAnimation
	dw DittoAnimation
	dw MettoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw TirtougaAnimation
	dw CarracostaAnimation
	dw ArchenAnimation
	dw ArcheopsAnimation
	dw TyruntAnimation
	dw TyrantrumAnimation
	dw AmauraAnimation
	dw AurorusAnimation
	dw RagingBoltAnimation
	dw GougingFireAnimation
	dw WalkingWakeAnimation
	dw GibleAnimation
	dw GabiteAnimation
	dw GarchompAnimation
	dw NecrozmaAnimation
	dw JirachiAnimation
	dw RowletAnimation
	dw DartrixAnimation
	dw DecidueyeAnimation
	dw FennekinAnimation
	dw BraixenAnimation
	dw DelphoxAnimation
	dw PiplupAnimation
	dw PrinplupAnimation
	dw EmpoleonAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw TarountulaAnimation
	dw SpidopsAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw GardevoirAnimation
	dw GalladeAnimation
	dw MissingNoAnimation
	dw LeafeonAnimation
	dw TinkatinkAnimation
	dw TinkatuffAnimation
	dw TinkatonAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw HoppipAnimation
	dw SkiploomAnimation
	dw JumpluffAnimation
	dw UmbreonRedAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw YanmegaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MisdreavusAnimation
	dw MismagiusAnimation
	dw UnownAnimation
	dw PhantumpAnimation
	dw TrevenantAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw WolfmanAnimation
	dw WarwolfAnimation
	dw StuffulAnimation
	dw BewearAnimation
	dw QwilfishAnimation
	dw NumpuffAnimation
	dw ScizorAnimation
	dw HeracrossAnimation
	dw SneaselAnimation
	dw WeavileAnimation
	dw RelicanthAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw MamoswineAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw MantineAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw CramorantAnimation
	dw TrapinchAnimation
	dw VibravaAnimation
	dw FlygonAnimation
	dw Porygon2Animation
	dw PorygonZAnimation
	dw SmeargleAnimation
	dw BlacephalonAnimation
	dw StakatakaAnimation
	dw ChinglingAnimation
	dw ChimechoAnimation
	dw KurstrawAnimation
	dw PangshiAnimation
	dw Zygarde10Animation
	dw Zygarde50Animation
	dw Zygarde100Animation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw GorochuAnimation
	dw SylveonAnimation
	dw SlitherWingAnimation
	assert_table_length NUM_POKEMON
