AnimationPointers:
	table_width 2
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw VenusaurAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw CaterpieAnimation
	dw MetapodAnimation
	dw ButterfreeAnimation
	dw WeedleAnimation
	dw KakunaAnimation
	dw BeedrillAnimation
	dw RookideeAnimation
	dw CorvisquireAnimation
	dw CorviknightAnimation
	dw ZigzagoonAnimation
	dw LinooneAnimation
	dw TaillowAnimation
	dw SwellowAnimation
	dw KotoraAnimation
	dw RaitoraAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw SandygastAnimation
	dw PalossandAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw GlimmetAnimation
	dw GlimmoraAnimation
	dw CutieflyAnimation
	dw RibombeeAnimation
	dw RinringAnimation
	dw BellerunAnimation
	dw OddishAnimation
	dw GloomAnimation
	dw VileplumeAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw LarvestaAnimation
	dw VolcaronaAnimation
	dw DrilburAnimation
	dw ExcadrillAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw WimpodAnimation
	dw GolisopodAnimation
	dw PetililAnimation
	dw LilligantAnimation
	dw LilligantHisuiAnimation
	dw OrthwormAnimation
	dw MimikyuAnimation
	dw PoliwagAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw HatennaAnimation
	dw HattremAnimation
	dw HattereneAnimation
	dw DedenneAnimation
	dw GolettAnimation
	dw GolurkAnimation
	dw BellsproutAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw SwavybellAnimation
	dw AronAnimation
	dw LaironAnimation
	dw AggronAnimation
	dw DarumakaAnimation
	dw DarmanitanAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw SlowkingAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw MagnezoneAnimation
	dw FarfetchDAnimation
	dw LuxwanAnimation
	dw ChatotAnimation
	dw HawluchaAnimation
	dw WailmerAnimation
	dw WailordAnimation
	dw SkrelpAnimation
	dw DragalgeAnimation
	dw ShellderAnimation
	dw CloysterAnimation
	dw TurbannAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw AbsolAnimation
	dw InkayAnimation
	dw MalamarAnimation
	dw ClauncherAnimation
	dw ClawitzerAnimation
	dw ImpidimpAnimation
	dw MorgremAnimation
	dw GrimmsnarlAnimation
	dw SpiritombAnimation
	dw CuboneAnimation
	dw MarowakAnimation
	dw LatiasAnimation
	dw LatiosAnimation
	dw LickitungAnimation
	dw LickikingAnimation
	dw VaroomAnimation
	dw RevavroomAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw RhyperiorAnimation
	dw ChanseyAnimation
	dw BlisseyAnimation
	dw TangelaAnimation
	dw TangorestAnimation
	dw BomseekerAnimation
	dw CorsasunAnimation
	dw AnchorageAnimation
	dw GrotessAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw ScytherAnimation
	dw JoltikAnimation
	dw GalvantulaAnimation
	dw PinsirAnimation
	dw PraxeAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw LaprasAnimation
	dw DittoAnimation
	dw MettoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw TirtougaAnimation
	dw CarracostaAnimation
	dw ArchenAnimation
	dw ArcheopsAnimation
	dw TyruntAnimation
	dw TyrantrumAnimation
	dw AmauraAnimation
	dw AurorusAnimation
	dw RagingBoltAnimation
	dw GougingFireAnimation
	dw WalkingWakeAnimation
	dw GibleAnimation
	dw GabiteAnimation
	dw GarchompAnimation
	dw NecrozmaAnimation
	dw MewAnimation
	dw RowletAnimation
	dw DartrixAnimation
	dw DecidueyeAnimation
	dw FennekinAnimation
	dw BraixenAnimation
	dw DelphoxAnimation
	dw PiplupAnimation
	dw PrinplupAnimation
	dw EmpoleonAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw GardevoirAnimation
	dw GalladeAnimation
	dw PichuAnimation
	dw CleffaAnimation
	dw TinkatinkAnimation
	dw TinkatuffAnimation
	dw TinkatonAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw HoppipAnimation
	dw SkiploomAnimation
	dw JumpluffAnimation
	dw AipomAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw YanmegaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MisdreavusAnimation
	dw MismagiusAnimation
	dw UnownAnimation
	dw PhantumpAnimation
	dw TrevenantAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw DunsparceAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw QwilfishAnimation
	dw NumpuffAnimation
	dw ScizorAnimation
	dw HeracrossAnimation
	dw SneaselAnimation
	dw WeavileAnimation
	dw UrsaringAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw MamoswineAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw MantineAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw StantlerAnimation
	dw Porygon2Animation
	dw PorygonZAnimation
	dw SmeargleAnimation
	dw BlacephalonAnimation
	dw StakatakaAnimation
	dw SmoochumAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw Zygarde10Animation
	dw Zygarde50Animation
	dw Zygarde100Animation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw TentacruelAnimation
	assert_table_length NUM_POKEMON
