BitmasksPointers:
	table_width 2
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw RookideeBitmasks
	dw CorvisquireBitmasks
	dw CorviknightBitmasks
	dw ZigzagoonBitmasks
	dw LinooneBitmasks
	dw TaillowBitmasks
	dw SwellowBitmasks
	dw KotoraBitmasks
	dw RaitoraBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandygastBitmasks
	dw PalossandBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw GlimmetBitmasks
	dw GlimmoraBitmasks
	dw CutieflyBitmasks
	dw RibombeeBitmasks
	dw RinringBitmasks
	dw BellerunBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw LarvestaBitmasks
	dw VolcaronaBitmasks
	dw DrilburBitmasks
	dw ExcadrillBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw WimpodBitmasks
	dw GolisopodBitmasks
	dw PetililBitmasks
	dw LilligantBitmasks
	dw LilligantHisuiBitmasks
	dw OrthwormBitmasks
	dw MimikyuBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw HatennaBitmasks
	dw HattremBitmasks
	dw HattereneBitmasks
	dw DedenneBitmasks
	dw GolettBitmasks
	dw GolurkBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw SwavybellBitmasks
	dw AronBitmasks
	dw LaironBitmasks
	dw AggronBitmasks
	dw DarumakaBitmasks
	dw DarmanitanBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw SlowkingBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw FarfetchDBitmasks
	dw LuxwanBitmasks
	dw ChatotBitmasks
	dw HawluchaBitmasks
	dw WailmerBitmasks
	dw WailordBitmasks
	dw SkrelpBitmasks
	dw DragalgeBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw TurbannBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw AbsolBitmasks
	dw InkayBitmasks
	dw MalamarBitmasks
	dw ClauncherBitmasks
	dw ClawitzerBitmasks
	dw ImpidimpBitmasks
	dw MorgremBitmasks
	dw GrimmsnarlBitmasks
	dw SpiritombBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw LatiasBitmasks
	dw LatiosBitmasks
	dw LickitungBitmasks
	dw LickikingBitmasks
	dw VaroomBitmasks
	dw RevavroomBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw RhyperiorBitmasks
	dw ChanseyBitmasks
	dw BlisseyBitmasks
	dw TangelaBitmasks
	dw TangorestBitmasks
	dw BomseekerBitmasks
	dw CorsasunBitmasks
	dw AnchorageBitmasks
	dw GrotessBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw ScytherBitmasks
	dw JoltikBitmasks
	dw GalvantulaBitmasks
	dw PinsirBitmasks
	dw PraxeBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw MettoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw TirtougaBitmasks
	dw CarracostaBitmasks
	dw ArchenBitmasks
	dw ArcheopsBitmasks
	dw TyruntBitmasks
	dw TyrantrumBitmasks
	dw AmauraBitmasks
	dw AurorusBitmasks
	dw RagingBoltBitmasks
	dw GougingFireBitmasks
	dw WalkingWakeBitmasks
	dw GibleBitmasks
	dw GabiteBitmasks
	dw GarchompBitmasks
	dw NecrozmaBitmasks
	dw MewBitmasks
	dw RowletBitmasks
	dw DartrixBitmasks
	dw DecidueyeBitmasks
	dw FennekinBitmasks
	dw BraixenBitmasks
	dw DelphoxBitmasks
	dw PiplupBitmasks
	dw PrinplupBitmasks
	dw EmpoleonBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw GalladeBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw TinkatinkBitmasks
	dw TinkatuffBitmasks
	dw TinkatonBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw UnownBitmasks
	dw PhantumpBitmasks
	dw TrevenantBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw QwilfishBitmasks
	dw NumpuffBitmasks
	dw ScizorBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw WeavileBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw MamoswineBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw MantineBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw StantlerBitmasks
	dw Porygon2Bitmasks
	dw PorygonZBitmasks
	dw SmeargleBitmasks
	dw BlacephalonBitmasks
	dw StakatakaBitmasks
	dw SmoochumBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw Zygarde10Bitmasks
	dw Zygarde50Bitmasks
	dw Zygarde100Bitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw TentacruelBitmasks
	assert_table_length NUM_POKEMON
