BitmasksPointers:
	table_width 2
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw TentacoolBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw SwavybellBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw SlowkingBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw FarfetchDBitmasks
	dw LuxwanBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw TurbannBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw LatiasBitmasks
	dw LatiosBitmasks
	dw LickitungBitmasks
	dw LickikingBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw RhyperiorBitmasks
	dw ChanseyBitmasks
	dw BlisseyBitmasks
	dw TangelaBitmasks
	dw TangorestBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GoldeenBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw ScytherBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw PraxeBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw MettoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw RagingBoltBitmasks
	dw GougingFireBitmasks
	dw WalkingWakeBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw NecrozmaBitmasks
	dw MewBitmasks
	dw RowletBitmasks
	dw DartrixBitmasks
	dw DecidueyeBitmasks
	dw FennekinBitmasks
	dw BraixenBitmasks
	dw DelphoxBitmasks
	dw PiplupBitmasks
	dw PrinplupBitmasks
	dw EmpoleonBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw GalladeBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw TinkatinkBitmasks
	dw TinkatuffBitmasks
	dw TinkatonBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw UnownBitmasks
	dw PhantumpBitmasks
	dw TrevenantBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw QwilfishBitmasks
	dw NumpuffBitmasks
	dw ScizorBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw WeavileBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw MamoswineBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw MantineBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw StantlerBitmasks
	dw Porygon2Bitmasks
	dw PorygonZBitmasks
	dw SmeargleBitmasks
	dw BlacephalonBitmasks
	dw StakatakaBitmasks
	dw SmoochumBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw Zygarde10Bitmasks
	dw Zygarde50Bitmasks
	dw Zygarde100Bitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw TentacruelBitmasks
	assert_table_length NUM_POKEMON
