FramesPointers:
	table_width 2
	dw TreeckoFrames
	dw GrovyleFrames
	dw SceptileFrames
	dw TorchicFrames
	dw CombuskenFrames
	dw BlazikenFrames
	dw MudkipFrames
	dw MarshtompFrames
	dw SwampertFrames
	dw GrubbinFrames
	dw CharjabugFrames
	dw VikavoltFrames
	dw VenipedeFrames
	dw WhirlipedeFrames
	dw ScolipedeFrames
	dw RookideeFrames
	dw CorvisquireFrames
	dw CorviknightFrames
	dw ZigzagoonFrames
	dw LinooneFrames
	dw TaillowFrames
	dw SwellowFrames
	dw KotoraFrames
	dw RaitoraFrames
	dw PikachuFrames
	dw RaichuFrames
	dw SandygastFrames
	dw PalossandFrames
	dw BudewFrames
	dw RoseliaFrames
	dw RoseradeFrames
	dw CharcadetFrames
	dw ArmarogueFrames
	dw CeruledgeFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw GlimmetFrames
	dw GlimmoraFrames
	dw CutieflyFrames
	dw RibombeeFrames
	dw RinringFrames
	dw BellerunFrames
	dw GavillainFrames
	dw CactriFrames
	dw SharpoonFrames
	dw ShroomishFrames
	dw BreloomFrames
	dw LarvestaFrames
	dw VolcaronaFrames
	dw DrilburFrames
	dw ExcadrillFrames
	dw MeowthFrames
	dw PersianFrames
	dw WimpodFrames
	dw GolisopodFrames
	dw PetililFrames
	dw LilligantFrames
	dw LilligantHisuiFrames
	dw OrthwormFrames
	dw MimikyuFrames
	dw SphealFrames
	dw SealeoFrames
	dw WalreinFrames
	dw HatennaFrames
	dw HattremFrames
	dw HattereneFrames
	dw DedenneFrames
	dw GolettFrames
	dw GolurkFrames
	dw BellsproutFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw SwavybellFrames
	dw AronFrames
	dw LaironFrames
	dw AggronFrames
	dw DarumakaFrames
	dw DarmanitanFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw SlowkingFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw FarfetchDFrames
	dw LuxwanFrames
	dw ChatotFrames
	dw HawluchaFrames
	dw WailmerFrames
	dw WailordFrames
	dw SkrelpFrames
	dw DragalgeFrames
	dw ShellderFrames
	dw CloysterFrames
	dw TurbannFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw AbsolFrames
	dw InkayFrames
	dw MalamarFrames
	dw ClauncherFrames
	dw ClawitzerFrames
	dw ImpidimpFrames
	dw MorgremFrames
	dw GrimmsnarlFrames
	dw SpiritombFrames
	dw CuboneFrames
	dw MarowakFrames
	dw LatiasFrames
	dw LatiosFrames
	dw LickitungFrames
	dw LickikingFrames
	dw VaroomFrames
	dw RevavroomFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw RhyperiorFrames
	dw ChanseyFrames
	dw BlisseyFrames
	dw TangelaFrames
	dw TangorestFrames
	dw BomseekerFrames
	dw CorsasunFrames
	dw AnchorageFrames
	dw GrotessFrames
	dw StaryuFrames
	dw StarmieFrames
	dw ScytherFrames
	dw JoltikFrames
	dw GalvantulaFrames
	dw PinsirFrames
	dw PraxeFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw FalinksFrames
	dw DittoFrames
	dw MettoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorygonFrames
	dw TirtougaFrames
	dw CarracostaFrames
	dw ArchenFrames
	dw ArcheopsFrames
	dw TyruntFrames
	dw TyrantrumFrames
	dw AmauraFrames
	dw AurorusFrames
	dw RagingBoltFrames
	dw GougingFireFrames
	dw WalkingWakeFrames
	dw GibleFrames
	dw GabiteFrames
	dw GarchompFrames
	dw NecrozmaFrames
	dw JirachiFrames
	dw RowletFrames
	dw DartrixFrames
	dw DecidueyeFrames
	dw FennekinFrames
	dw BraixenFrames
	dw DelphoxFrames
	dw PiplupFrames
	dw PrinplupFrames
	dw EmpoleonFrames
	dw SentretFrames
	dw FurretFrames
	dw SwabluFrames
	dw AltariaFrames
	dw TarountulaFrames
	dw SpidopsFrames
	dw RaltsFrames
	dw KirliaFrames
	dw GardevoirFrames
	dw GalladeFrames
	dw PichuFrames
	dw CleffaFrames
	dw TinkatinkFrames
	dw TinkatuffFrames
	dw TinkatonFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw MarillFrames
	dw AzumarillFrames
	dw HoppipFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw KecleonFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw YanmegaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MisdreavusFrames
	dw MismagiusFrames
	dw UnownFrames
	dw PhantumpFrames
	dw TrevenantFrames
	dw PinecoFrames
	dw ForretressFrames
	dw WolfmanFrames
	dw WarwolfFrames
	dw StuffulFrames
	dw BewearFrames
	dw QwilfishFrames
	dw NumpuffFrames
	dw ScizorFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw WeavileFrames
	dw RelicanthFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw MantineFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw CramorantFrames
	dw TrapinchFrames
	dw VibravaFrames
	dw FlygonFrames
	dw Porygon2Frames
	dw PorygonZFrames
	dw SmeargleFrames
	dw BlacephalonFrames
	dw StakatakaFrames
	dw ChinglingFrames
	dw ChimechoFrames
	dw KurstrawFrames
	dw PangshiFrames
	dw Zygarde10Frames
	dw Zygarde50Frames
	dw Zygarde100Frames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	dw GorochuFrames
	dw SylveonFrames
	dw SlitherWingFrames
	assert_table_length NUM_POKEMON
