FramesPointers:
	table_width 2
	dw BulbasaurFrames
	dw IvysaurFrames
	dw VenusaurFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw CharizardFrames
	dw SquirtleFrames
	dw WartortleFrames
	dw BlastoiseFrames
	dw CaterpieFrames
	dw MetapodFrames
	dw ButterfreeFrames
	dw WeedleFrames
	dw KakunaFrames
	dw BeedrillFrames
	dw PidgeyFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw RattataFrames
	dw RaticateFrames
	dw SpearowFrames
	dw FearowFrames
	dw EkansFrames
	dw ArbokFrames
	dw PikachuFrames
	dw RaichuFrames
	dw SandshrewFrames
	dw SandslashFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw VulpixFrames
	dw NinetalesFrames
	dw JigglypuffFrames
	dw WigglytuffFrames
	dw ZubatFrames
	dw GolbatFrames
	dw OddishFrames
	dw GloomFrames
	dw VileplumeFrames
	dw ParasFrames
	dw ParasectFrames
	dw VenonatFrames
	dw VenomothFrames
	dw DiglettFrames
	dw DugtrioFrames
	dw MeowthFrames
	dw PersianFrames
	dw PsyduckFrames
	dw GolduckFrames
	dw MankeyFrames
	dw PrimeapeFrames
	dw TentacoolFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw BellsproutFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw SwavybellFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw SlowkingFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw FarfetchDFrames
	dw LuxwanFrames
	dw DoduoFrames
	dw DodrioFrames
	dw SeelFrames
	dw DewgongFrames
	dw GrimerFrames
	dw MukFrames
	dw ShellderFrames
	dw CloysterFrames
	dw TurbannFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw DrowzeeFrames
	dw HypnoFrames
	dw KrabbyFrames
	dw KinglerFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw CuboneFrames
	dw MarowakFrames
	dw LatiasFrames
	dw LatiosFrames
	dw LickitungFrames
	dw LickikingFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw RhyperiorFrames
	dw ChanseyFrames
	dw BlisseyFrames
	dw TangelaFrames
	dw TangorestFrames
	dw KangaskhanFrames
	dw HorseaFrames
	dw SeadraFrames
	dw GoldeenFrames
	dw StaryuFrames
	dw StarmieFrames
	dw ScytherFrames
	dw ElectabuzzFrames
	dw MagmarFrames
	dw PinsirFrames
	dw PraxeFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw DittoFrames
	dw MettoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorygonFrames
	dw OmanyteFrames
	dw OmastarFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw AerodactylFrames
	dw SnorlaxFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw RagingBoltFrames
	dw GougingFireFrames
	dw WalkingWakeFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw NecrozmaFrames
	dw MewFrames
	dw RowletFrames
	dw DartrixFrames
	dw DecidueyeFrames
	dw FennekinFrames
	dw BraixenFrames
	dw DelphoxFrames
	dw PiplupFrames
	dw PrinplupFrames
	dw EmpoleonFrames
	dw SentretFrames
	dw FurretFrames
	dw HoothootFrames
	dw NoctowlFrames
	dw LedybaFrames
	dw LedianFrames
	dw RaltsFrames
	dw KirliaFrames
	dw GardevoirFrames
	dw GalladeFrames
	dw PichuFrames
	dw CleffaFrames
	dw TinkatinkFrames
	dw TinkatuffFrames
	dw TinkatonFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw MarillFrames
	dw AzumarillFrames
	dw HoppipFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw AipomFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw YanmegaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MisdreavusFrames
	dw MismagiusFrames
	dw UnownFrames
	dw PhantumpFrames
	dw TrevenantFrames
	dw PinecoFrames
	dw ForretressFrames
	dw DunsparceFrames
	dw GligarFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw QwilfishFrames
	dw NumpuffFrames
	dw ScizorFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw WeavileFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw MantineFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw StantlerFrames
	dw Porygon2Frames
	dw PorygonZFrames
	dw SmeargleFrames
	dw BlacephalonFrames
	dw StakatakaFrames
	dw SmoochumFrames
	dw ElekidFrames
	dw MagbyFrames
	dw MiltankFrames
	dw Zygarde10Frames
	dw Zygarde50Frames
	dw Zygarde100Frames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	dw TentacruelFrames
	assert_table_length NUM_POKEMON
