FramesPointers:
	table_width 2
	dw BulbasaurFrames
	dw IvysaurFrames
	dw VenusaurFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw CharizardFrames
	dw SquirtleFrames
	dw WartortleFrames
	dw BlastoiseFrames
	dw CaterpieFrames
	dw MetapodFrames
	dw ButterfreeFrames
	dw WeedleFrames
	dw KakunaFrames
	dw BeedrillFrames
	dw RookideeFrames
	dw CorvisquireFrames
	dw CorviknightFrames
	dw ZigzagoonFrames
	dw LinooneFrames
	dw TaillowFrames
	dw SwellowFrames
	dw KotoraFrames
	dw RaitoraFrames
	dw PikachuFrames
	dw RaichuFrames
	dw SandygastFrames
	dw PalossandFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw GlimmetFrames
	dw GlimmoraFrames
	dw CutieflyFrames
	dw RibombeeFrames
	dw RinringFrames
	dw BellerunFrames
	dw OddishFrames
	dw GloomFrames
	dw VileplumeFrames
	dw ShroomishFrames
	dw BreloomFrames
	dw LarvestaFrames
	dw VolcaronaFrames
	dw DrilburFrames
	dw ExcadrillFrames
	dw MeowthFrames
	dw PersianFrames
	dw WimpodFrames
	dw GolisopodFrames
	dw PetililFrames
	dw LilligantFrames
	dw LilligantHisuiFrames
	dw OrthwormFrames
	dw MimikyuFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw HatennaFrames
	dw HattremFrames
	dw HattereneFrames
	dw DedenneFrames
	dw GolettFrames
	dw GolurkFrames
	dw BellsproutFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw SwavybellFrames
	dw AronFrames
	dw LaironFrames
	dw AggronFrames
	dw DarumakaFrames
	dw DarmanitanFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw SlowkingFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw FarfetchDFrames
	dw LuxwanFrames
	dw ChatotFrames
	dw HawluchaFrames
	dw WailmerFrames
	dw WailordFrames
	dw SkrelpFrames
	dw DragalgeFrames
	dw ShellderFrames
	dw CloysterFrames
	dw TurbannFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw AbsolFrames
	dw InkayFrames
	dw MalamarFrames
	dw ClauncherFrames
	dw ClawitzerFrames
	dw ImpidimpFrames
	dw MorgremFrames
	dw GrimmsnarlFrames
	dw SpiritombFrames
	dw CuboneFrames
	dw MarowakFrames
	dw LatiasFrames
	dw LatiosFrames
	dw LickitungFrames
	dw LickikingFrames
	dw VaroomFrames
	dw RevavroomFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw RhyperiorFrames
	dw ChanseyFrames
	dw BlisseyFrames
	dw TangelaFrames
	dw TangorestFrames
	dw BomseekerFrames
	dw CorsasunFrames
	dw AnchorageFrames
	dw GrotessFrames
	dw StaryuFrames
	dw StarmieFrames
	dw ScytherFrames
	dw JoltikFrames
	dw GalvantulaFrames
	dw PinsirFrames
	dw PraxeFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw DittoFrames
	dw MettoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorygonFrames
	dw TirtougaFrames
	dw CarracostaFrames
	dw ArchenFrames
	dw ArcheopsFrames
	dw TyruntFrames
	dw TyrantrumFrames
	dw AmauraFrames
	dw AurorusFrames
	dw RagingBoltFrames
	dw GougingFireFrames
	dw WalkingWakeFrames
	dw GibleFrames
	dw GabiteFrames
	dw GarchompFrames
	dw NecrozmaFrames
	dw MewFrames
	dw RowletFrames
	dw DartrixFrames
	dw DecidueyeFrames
	dw FennekinFrames
	dw BraixenFrames
	dw DelphoxFrames
	dw PiplupFrames
	dw PrinplupFrames
	dw EmpoleonFrames
	dw SentretFrames
	dw FurretFrames
	dw HoothootFrames
	dw NoctowlFrames
	dw LedybaFrames
	dw LedianFrames
	dw RaltsFrames
	dw KirliaFrames
	dw GardevoirFrames
	dw GalladeFrames
	dw PichuFrames
	dw CleffaFrames
	dw TinkatinkFrames
	dw TinkatuffFrames
	dw TinkatonFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw MarillFrames
	dw AzumarillFrames
	dw HoppipFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw AipomFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw YanmegaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MisdreavusFrames
	dw MismagiusFrames
	dw UnownFrames
	dw PhantumpFrames
	dw TrevenantFrames
	dw PinecoFrames
	dw ForretressFrames
	dw DunsparceFrames
	dw GligarFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw QwilfishFrames
	dw NumpuffFrames
	dw ScizorFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw WeavileFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw MantineFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw StantlerFrames
	dw Porygon2Frames
	dw PorygonZFrames
	dw SmeargleFrames
	dw BlacephalonFrames
	dw StakatakaFrames
	dw SmoochumFrames
	dw ElekidFrames
	dw MagbyFrames
	dw MiltankFrames
	dw Zygarde10Frames
	dw Zygarde50Frames
	dw Zygarde100Frames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	dw TentacruelFrames
	assert_table_length NUM_POKEMON
