AnimationIdlePointers:
	table_width 2
	dw BulbasaurAnimationIdle
	dw IvysaurAnimationIdle
	dw VenusaurAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw CharizardAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw BlastoiseAnimationIdle
	dw CaterpieAnimationIdle
	dw MetapodAnimationIdle
	dw ButterfreeAnimationIdle
	dw WeedleAnimationIdle
	dw KakunaAnimationIdle
	dw BeedrillAnimationIdle
	dw RookideeAnimationIdle
	dw CorvisquireAnimationIdle
	dw CorviknightAnimationIdle
	dw ZigzagoonAnimationIdle
	dw LinooneAnimationIdle
	dw TaillowAnimationIdle
	dw SwellowAnimationIdle
	dw KotoraAnimationIdle
	dw RaitoraAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw SandygastAnimationIdle
	dw PalossandAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw GlimmetAnimationIdle
	dw GlimmoraAnimationIdle
	dw CutieflyAnimationIdle
	dw RibombeeAnimationIdle
	dw RinringAnimationIdle
	dw BellerunAnimationIdle
	dw OddishAnimationIdle
	dw GloomAnimationIdle
	dw VileplumeAnimationIdle
	dw ShroomishAnimationIdle
	dw BreloomAnimationIdle
	dw LarvestaAnimationIdle
	dw VolcaronaAnimationIdle
	dw DrilburAnimationIdle
	dw ExcadrillAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw WimpodAnimationIdle
	dw GolisopodAnimationIdle
	dw PetililAnimationIdle
	dw LilligantAnimationIdle
	dw OrthwormAnimationIdle
	dw MimikyuAnimationIdle
	dw PoliwagAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw HatennaAnimationIdle
	dw HattremAnimationIdle
	dw HattereneAnimationIdle
	dw DedenneAnimationIdle
	dw GolettAnimationIdle
	dw GolurkAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw SwavybellAnimationIdle
	dw LilligantHisuiAnimationIdle
	dw TentacruelAnimationIdle
	dw AronAnimationIdle
	dw LaironAnimationIdle
	dw AggronAnimationIdle
	dw DarumakaAnimationIdle
	dw DarmanitanAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw SlowkingAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw MagnezoneAnimationIdle
	dw FarfetchDAnimationIdle
	dw LuxwanAnimationIdle
	dw ChatotAnimationIdle
	dw HawluchaAnimationIdle
	dw WailmerAnimationIdle
	dw WailordAnimationIdle
	dw SkrelpAnimationIdle
	dw DragalgeAnimationIdle
	dw ShellderAnimationIdle
	dw CloysterAnimationIdle
	dw TurbannAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw AbsolAnimationIdle
	dw InkayAnimationIdle
	dw MalamarAnimationIdle
	dw ClauncherAnimationIdle
	dw ClawitzerAnimationIdle
	dw ImpidimpAnimationIdle
	dw MorgremAnimationIdle
	dw GrimmsnarlAnimationIdle
	dw SpiritombAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw LatiasAnimationIdle
	dw LatiosAnimationIdle
	dw LickitungAnimationIdle
	dw LickikingAnimationIdle
	dw VaroomAnimationIdle
	dw RevavroomAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw RhyperiorAnimationIdle
	dw ChanseyAnimationIdle
	dw BlisseyAnimationIdle
	dw TangelaAnimationIdle
	dw TangorestAnimationIdle
	dw BomseekerAnimationIdle
	dw CorsasunAnimationIdle
	dw AnchorageAnimationIdle
	dw GrotessAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw ScytherAnimationIdle
	dw JoltikAnimationIdle
	dw GalvantulaAnimationIdle
	dw PinsirAnimationIdle
	dw PraxeAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw DittoAnimationIdle
	dw MettoAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw PorygonAnimationIdle
	dw TirtougaAnimationIdle
	dw CarracostaAnimationIdle
	dw ArchenAnimationIdle
	dw ArcheopsAnimationIdle
	dw TyruntAnimationIdle
	dw TyrantrumAnimationIdle
	dw AmauraAnimationIdle
	dw AurorusAnimationIdle
	dw RagingBoltAnimationIdle
	dw GougingFireAnimationIdle
	dw WalkingWakeAnimationIdle
	dw GibleAnimationIdle
	dw GabiteAnimationIdle
	dw GarchompAnimationIdle
	dw NecrozmaAnimationIdle
	dw MewAnimationIdle
	dw RowletAnimationIdle
	dw DartrixAnimationIdle
	dw DecidueyeAnimationIdle
	dw FennekinAnimationIdle
	dw BraixenAnimationIdle
	dw DelphoxAnimationIdle
	dw PiplupAnimationIdle
	dw PrinplupAnimationIdle
	dw EmpoleonAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw HoothootAnimationIdle
	dw NoctowlAnimationIdle
	dw LedybaAnimationIdle
	dw LedianAnimationIdle
	dw RaltsAnimationIdle
	dw KirliaAnimationIdle
	dw GardevoirAnimationIdle
	dw GalladeAnimationIdle
	dw PichuAnimationIdle
	dw CleffaAnimationIdle
	dw TinkatinkAnimationIdle
	dw TinkatuffAnimationIdle
	dw TinkatonAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw AipomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw YanmaAnimationIdle
	dw YanmegaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw MisdreavusAnimationIdle
	dw MismagiusAnimationIdle
	dw UnownAnimationIdle
	dw PhantumpAnimationIdle
	dw TrevenantAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw DunsparceAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw SnubbullAnimationIdle
	dw QwilfishAnimationIdle
	dw ScizorAnimationIdle
	dw NumpuffAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw WeavileAnimationIdle
	dw UrsaringAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw MamoswineAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw MantineAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw KingdraAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw StantlerAnimationIdle
	dw Porygon2AnimationIdle
	dw PorygonZAnimationIdle
	dw SmeargleAnimationIdle
	dw BlacephalonAnimationIdle
	dw StakatakaAnimationIdle
	dw SmoochumAnimationIdle
	dw ElekidAnimationIdle
	dw MagbyAnimationIdle
	dw MiltankAnimationIdle
	dw Zygarde10AnimationIdle
	dw Zygarde50AnimationIdle
	dw Zygarde100AnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	assert_table_length NUM_POKEMON
