; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in layout.link.


SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"


SECTION "Pics 1", ROMX

HoOhFrontpic:        INCBIN "gfx/pokemon/ho_oh/front.animated.2bpp.lz"
GolurkFrontpic:     INCBIN "gfx/pokemon/golurk/front.animated.2bpp.lz"
GlimmoraFrontpic:   INCBIN "gfx/pokemon/glimmora/front.animated.2bpp.lz"
EmpoleonFrontpic:  INCBIN "gfx/pokemon/empoleon/front.animated.2bpp.lz"
CeruledgeFrontpic:    INCBIN "gfx/pokemon/ceruledge/front.animated.2bpp.lz"
Zygarde10Frontpic:      INCBIN "gfx/pokemon/zygarde10/front.animated.2bpp.lz"
LugiaFrontpic:       INCBIN "gfx/pokemon/lugia/front.animated.2bpp.lz"
RagingBoltFrontpic:    INCBIN "gfx/pokemon/ragingbolt/front.animated.2bpp.lz"
LuxwanFrontpic:      INCBIN "gfx/pokemon/luxwan/front.animated.2bpp.lz"
SceptileFrontpic:    INCBIN "gfx/pokemon/sceptile/front.animated.2bpp.lz"
Zygarde50Frontpic:       INCBIN "gfx/pokemon/zygarde50/front.animated.2bpp.lz"
Zygarde100Frontpic:     INCBIN "gfx/pokemon/zygarde100/front.animated.2bpp.lz"
DelphoxFrontpic:  INCBIN "gfx/pokemon/delphox/front.animated.2bpp.lz"


SECTION "Pics 2", ROMX

SwampertFrontpic:   INCBIN "gfx/pokemon/swampert/front.animated.2bpp.lz"
DarmanitanFrontpic:    INCBIN "gfx/pokemon/darmanitan/front.animated.2bpp.lz"
DecidueyeFrontpic:    INCBIN "gfx/pokemon/decidueye/front.animated.2bpp.lz"
RoseradeFrontpic:   INCBIN "gfx/pokemon/roserade/front.animated.2bpp.lz"
LatiasFrontpic:   INCBIN "gfx/pokemon/latias/front.animated.2bpp.lz"
ScizorFrontpic:      INCBIN "gfx/pokemon/scizor/front.animated.2bpp.lz"
ScolipedeFrontpic:    INCBIN "gfx/pokemon/scolipede/front.animated.2bpp.lz"
MimikyuFrontpic:    INCBIN "gfx/pokemon/mimikyu/front.animated.2bpp.lz"
TyranitarFrontpic:   INCBIN "gfx/pokemon/tyranitar/front.animated.2bpp.lz"
WalkingWakeFrontpic:     INCBIN "gfx/pokemon/walkingwake/front.animated.2bpp.lz"
GougingFireFrontpic:      INCBIN "gfx/pokemon/gougingfire/front.animated.2bpp.lz"
RaitoraFrontpic:       INCBIN "gfx/pokemon/raitora/front.animated.2bpp.lz"
NecrozmaFrontpic:      INCBIN "gfx/pokemon/necrozma/front.animated.2bpp.lz"
SwellowFrontpic:      INCBIN "gfx/pokemon/swellow/front.animated.2bpp.lz"
BlazikenFrontpic:   INCBIN "gfx/pokemon/blaziken/front.animated.2bpp.lz"
BraixenFrontpic:     INCBIN "gfx/pokemon/braixen/front.animated.2bpp.lz"


SECTION "Pics 3", ROMX

StuffulFrontpic:     INCBIN "gfx/pokemon/stufful/front.animated.2bpp.lz"
HattereneFrontpic:    INCBIN "gfx/pokemon/hatterene/front.animated.2bpp.lz"
GyaradosFrontpic:    INCBIN "gfx/pokemon/gyarados/front.animated.2bpp.lz"
BomseekerFrontpic:  INCBIN "gfx/pokemon/bomseeker/front.animated.2bpp.lz"
RhydonFrontpic:      INCBIN "gfx/pokemon/rhydon/front.animated.2bpp.lz"
GolisopodFrontpic:     INCBIN "gfx/pokemon/golisopod/front.animated.2bpp.lz"
RhyhornFrontpic:     INCBIN "gfx/pokemon/rhyhorn/front.animated.2bpp.lz"
CorviknightFrontpic:     INCBIN "gfx/pokemon/corviknight/front.animated.2bpp.lz"
SlowbroFrontpic:     INCBIN "gfx/pokemon/slowbro/front.animated.2bpp.lz"
VikavoltFrontpic:  INCBIN "gfx/pokemon/vikavolt/front.animated.2bpp.lz"
RevavroomFrontpic:     INCBIN "gfx/pokemon/revavroom/front.animated.2bpp.lz"
CloysterFrontpic:    INCBIN "gfx/pokemon/cloyster/front.animated.2bpp.lz"
WailordFrontpic:     INCBIN "gfx/pokemon/wailord/front.animated.2bpp.lz"
VictreebelFrontpic:  INCBIN "gfx/pokemon/victreebel/front.animated.2bpp.lz"
RaichuFrontpic:      INCBIN "gfx/pokemon/raichu/front.animated.2bpp.lz"
LilligantFrontpic:    INCBIN "gfx/pokemon/lilligant/front.animated.2bpp.lz"
CarracostaBackpic:      INCBIN "gfx/pokemon/carracosta/back.2bpp.lz"


SECTION "Pics 4", ROMX

HawluchaFrontpic:      INCBIN "gfx/pokemon/hawlucha/front.animated.2bpp.lz"
SlowkingFrontpic:    INCBIN "gfx/pokemon/slowking/front.animated.2bpp.lz"
StakatakaFrontpic:   INCBIN "gfx/pokemon/stakataka/front.animated.2bpp.lz"
AbsolFrontpic:        INCBIN "gfx/pokemon/absol/front.animated.2bpp.lz"
BlisseyFrontpic:     INCBIN "gfx/pokemon/blissey/front.animated.2bpp.lz"
GolettFrontpic:     INCBIN "gfx/pokemon/golett/front.animated.2bpp.lz"
GarchompFrontpic:   INCBIN "gfx/pokemon/garchomp/front.animated.2bpp.lz"
WalreinFrontpic:   INCBIN "gfx/pokemon/walrein/front.animated.2bpp.lz"
ScytherFrontpic:     INCBIN "gfx/pokemon/scyther/front.animated.2bpp.lz"
TyruntFrontpic:  INCBIN "gfx/pokemon/tyrunt/front.animated.2bpp.lz"
TangorestFrontpic:     INCBIN "gfx/pokemon/tangorest/front.animated.2bpp.lz"
DragalgeFrontpic:         INCBIN "gfx/pokemon/dragalge/front.animated.2bpp.lz"
PrinplupFrontpic:    INCBIN "gfx/pokemon/prinplup/front.animated.2bpp.lz"
MalamarFrontpic:       INCBIN "gfx/pokemon/malamar/front.animated.2bpp.lz"
ArmarogueFrontpic:    INCBIN "gfx/pokemon/armarogue/front.animated.2bpp.lz"
PalossandFrontpic:   INCBIN "gfx/pokemon/palossand/front.animated.2bpp.lz"
JolteonFrontpic:     INCBIN "gfx/pokemon/jolteon/front.animated.2bpp.lz"

SECTION "Pics 5", ROMX

BellerunFrontpic:      INCBIN "gfx/pokemon/bellerun/front.animated.2bpp.lz"
ClawitzerFrontpic:     INCBIN "gfx/pokemon/clawitzer/front.animated.2bpp.lz"
GrimmsnarlFrontpic:   INCBIN "gfx/pokemon/grimmsnarl/front.animated.2bpp.lz"
MagcargoFrontpic:    INCBIN "gfx/pokemon/magcargo/front.animated.2bpp.lz"
PersianFrontpic:     INCBIN "gfx/pokemon/persian/front.animated.2bpp.lz"
FlygonFrontpic:    INCBIN "gfx/pokemon/flygon/front.animated.2bpp.lz"
LinooneFrontpic:    INCBIN "gfx/pokemon/linoone/front.animated.2bpp.lz"
VolcaronaFrontpic:    INCBIN "gfx/pokemon/volcarona/front.animated.2bpp.lz"
PraxeFrontpic:    INCBIN "gfx/pokemon/praxe/front.animated.2bpp.lz"
JoltikFrontpic:  INCBIN "gfx/pokemon/joltik/front.animated.2bpp.lz"
MantineFrontpic:     INCBIN "gfx/pokemon/mantine/front.animated.2bpp.lz"
GastlyFrontpic:      INCBIN "gfx/pokemon/gastly/front.animated.2bpp.lz"
AzumarillFrontpic:   INCBIN "gfx/pokemon/azumarill/front.animated.2bpp.lz"
BreloomFrontpic:    INCBIN "gfx/pokemon/breloom/front.animated.2bpp.lz"
LickikingFrontpic:      INCBIN "gfx/pokemon/lickiking/front.animated.2bpp.lz"
HeracrossFrontpic:   INCBIN "gfx/pokemon/heracross/front.animated.2bpp.lz"


SECTION "Pics 6", ROMX

KirliaFrontpic:     INCBIN "gfx/pokemon/kirlia/front.animated.2bpp.lz"
AltariaFrontpic:     INCBIN "gfx/pokemon/altaria/front.animated.2bpp.lz"
MarshtompFrontpic:   INCBIN "gfx/pokemon/marshtomp/front.animated.2bpp.lz"
FalinksFrontpic:      INCBIN "gfx/pokemon/falinks/front.animated.2bpp.lz"
SealeoFrontpic:   INCBIN "gfx/pokemon/sealeo/front.animated.2bpp.lz"
RelicanthFrontpic:    INCBIN "gfx/pokemon/relicanth/front.animated.2bpp.lz"
HoundoomFrontpic:    INCBIN "gfx/pokemon/houndoom/front.animated.2bpp.lz"
AmpharosFrontpic:    INCBIN "gfx/pokemon/ampharos/front.animated.2bpp.lz"
RoseliaFrontpic:    INCBIN "gfx/pokemon/roselia/front.animated.2bpp.lz"
FlareonFrontpic:     INCBIN "gfx/pokemon/flareon/front.animated.2bpp.lz"
FarfetchDFrontpic:   INCBIN "gfx/pokemon/farfetch_d/front.animated.2bpp.lz"
SharpoonFrontpic:   INCBIN "gfx/pokemon/sharpoon/front.animated.2bpp.lz"
DartrixFrontpic:     INCBIN "gfx/pokemon/dartrix/front.animated.2bpp.lz"
GalvantulaFrontpic:      INCBIN "gfx/pokemon/galvantula/front.animated.2bpp.lz"
GorochuFrontpic:  INCBIN "gfx/pokemon/gorochu/front.animated.2bpp.lz"
ChimechoFrontpic:      INCBIN "gfx/pokemon/chimecho/front.animated.2bpp.lz"
JumpluffFrontpic:    INCBIN "gfx/pokemon/jumpluff/front.animated.2bpp.lz"
MarowakFrontpic:     INCBIN "gfx/pokemon/marowak/front.animated.2bpp.lz"
GlimmetFrontpic:      INCBIN "gfx/pokemon/glimmet/front.animated.2bpp.lz"
WarwolfFrontpic:      INCBIN "gfx/pokemon/warwolf/front.animated.2bpp.lz"
WolfmanFrontpic:   INCBIN "gfx/pokemon/wolfman/front.animated.2bpp.lz"


SECTION "Pics 7", ROMX

VaporeonFrontpic:    INCBIN "gfx/pokemon/vaporeon/front.animated.2bpp.lz"
InkayFrontpic:     INCBIN "gfx/pokemon/inkay/front.animated.2bpp.lz"
SneaselFrontpic:     INCBIN "gfx/pokemon/sneasel/front.animated.2bpp.lz"
TyrantrumFrontpic:     INCBIN "gfx/pokemon/tyrantrum/front.animated.2bpp.lz"
RibombeeFrontpic:  INCBIN "gfx/pokemon/ribombee/front.animated.2bpp.lz"
YanmaFrontpic:       INCBIN "gfx/pokemon/yanma/front.animated.2bpp.lz"
SmeargleFrontpic:    INCBIN "gfx/pokemon/smeargle/front.animated.2bpp.lz"
ClefableFrontpic:    INCBIN "gfx/pokemon/clefable/front.animated.2bpp.lz"
DarumakaFrontpic:      INCBIN "gfx/pokemon/darumaka/front.animated.2bpp.lz"
LaironFrontpic:    INCBIN "gfx/pokemon/lairon/front.animated.2bpp.lz"
StarmieFrontpic:     INCBIN "gfx/pokemon/starmie/front.animated.2bpp.lz"
CorvisquireFrontpic:   INCBIN "gfx/pokemon/corvisquire/front.animated.2bpp.lz"
TarountulaFrontpic:      INCBIN "gfx/pokemon/tarountula/front.animated.2bpp.lz"
GengarFrontpic:      INCBIN "gfx/pokemon/gengar/front.animated.2bpp.lz"
CarracostaFrontpic:     INCBIN "gfx/pokemon/carracosta/front.animated.2bpp.lz"
PiloswineFrontpic:   INCBIN "gfx/pokemon/piloswine/front.animated.2bpp.lz"
ExcadrillFrontpic:     INCBIN "gfx/pokemon/excadrill/front.animated.2bpp.lz"
MagnetonFrontpic:    INCBIN "gfx/pokemon/magneton/front.animated.2bpp.lz"
GabiteFrontpic:   INCBIN "gfx/pokemon/gabite/front.animated.2bpp.lz"
ForretressFrontpic:  INCBIN "gfx/pokemon/forretress/front.animated.2bpp.lz"
TinkatinkFrontpic:     INCBIN "gfx/pokemon/tinkatink/front.animated.2bpp.lz"
BomseekerBackpic:   INCBIN "gfx/pokemon/bomseeker/back.2bpp.lz"


SECTION "Pics 8", ROMX

WailmerFrontpic:        INCBIN "gfx/pokemon/wailmer/front.animated.2bpp.lz"
GardevoirFrontpic:      INCBIN "gfx/pokemon/gardevoir/front.animated.2bpp.lz"
ChanseyFrontpic:     INCBIN "gfx/pokemon/chansey/front.animated.2bpp.lz"
TangelaFrontpic:     INCBIN "gfx/pokemon/tangela/front.animated.2bpp.lz"
BewearFrontpic:    INCBIN "gfx/pokemon/bewear/front.animated.2bpp.lz"
PangshiFrontpic:     INCBIN "gfx/pokemon/pangshi/front.animated.2bpp.lz"
HaunterFrontpic:     INCBIN "gfx/pokemon/haunter/front.animated.2bpp.lz"
SunfloraFrontpic:    INCBIN "gfx/pokemon/sunflora/front.animated.2bpp.lz"
UmbreonFrontpic:     INCBIN "gfx/pokemon/umbreon/front.animated.2bpp.lz"
RowletFrontpic:   INCBIN "gfx/pokemon/rowlet/front.animated.2bpp.lz"
GrotessFrontpic:     INCBIN "gfx/pokemon/grotess/front.animated.2bpp.lz"
EspeonFrontpic:      INCBIN "gfx/pokemon/espeon/front.animated.2bpp.lz"
TinkatonFrontpic:        INCBIN "gfx/pokemon/tinkaton/front.animated.2bpp.lz"
JirachiFrontpic:         INCBIN "gfx/pokemon/jirachi/front.animated.2bpp.lz"
OctilleryFrontpic:   INCBIN "gfx/pokemon/octillery/front.animated.2bpp.lz"
SpidopsFrontpic:      INCBIN "gfx/pokemon/spidops/front.animated.2bpp.lz"
CactriFrontpic:       INCBIN "gfx/pokemon/cactri/front.animated.2bpp.lz"
FlaaffyFrontpic:     INCBIN "gfx/pokemon/flaaffy/front.animated.2bpp.lz"
GrovyleFrontpic:     INCBIN "gfx/pokemon/grovyle/front.animated.2bpp.lz"
FurretFrontpic:      INCBIN "gfx/pokemon/furret/front.animated.2bpp.lz"
FennekinFrontpic:   INCBIN "gfx/pokemon/fennekin/front.animated.2bpp.lz"
LatiosFrontpic:  INCBIN "gfx/pokemon/latios/front.animated.2bpp.lz"
QuagsireFrontpic:    INCBIN "gfx/pokemon/quagsire/front.animated.2bpp.lz"


SECTION "Pics 9", ROMX

KotoraFrontpic:       INCBIN "gfx/pokemon/kotora/front.animated.2bpp.lz"
MettoFrontpic:   INCBIN "gfx/pokemon/metto/front.animated.2bpp.lz"
PikachuFrontpic:     INCBIN "gfx/pokemon/pikachu/front.animated.2bpp.lz"
AnchorageFrontpic:      INCBIN "gfx/pokemon/anchorage/front.animated.2bpp.lz"
KurstrawFrontpic:       INCBIN "gfx/pokemon/kurstraw/front.animated.2bpp.lz"
WeepinbellFrontpic:  INCBIN "gfx/pokemon/weepinbell/front.animated.2bpp.lz"
PiplupFrontpic:    INCBIN "gfx/pokemon/piplup/front.animated.2bpp.lz"
MamoswineFrontpic:     INCBIN "gfx/pokemon/mamoswine/front.animated.2bpp.lz"
FirebreatherPic:     INCBIN "gfx/trainers/firebreather.2bpp.lz"
DedenneFrontpic:      INCBIN "gfx/pokemon/dedenne/front.animated.2bpp.lz"
AmauraFrontpic:    INCBIN "gfx/pokemon/amaura/front.animated.2bpp.lz"
ZigzagoonFrontpic:     INCBIN "gfx/pokemon/zigzagoon/front.animated.2bpp.lz"
ChampionPic:         INCBIN "gfx/trainers/champion.2bpp.lz"
TaillowFrontpic:     INCBIN "gfx/pokemon/taillow/front.animated.2bpp.lz"
MagikarpFrontpic:    INCBIN "gfx/pokemon/magikarp/front.animated.2bpp.lz"
TorchicFrontpic:  INCBIN "gfx/pokemon/torchic/front.animated.2bpp.lz"
CuboneFrontpic:      INCBIN "gfx/pokemon/cubone/front.animated.2bpp.lz"
BlackbeltTPic:       INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
BikerPic:            INCBIN "gfx/trainers/biker.2bpp.lz"
CharcadetFrontpic:    INCBIN "gfx/pokemon/charcadet/front.animated.2bpp.lz"
PorygonFrontpic:     INCBIN "gfx/pokemon/porygon/front.animated.2bpp.lz"
BrunoPic:            INCBIN "gfx/trainers/bruno.2bpp.lz"
SkrelpFrontpic:      INCBIN "gfx/pokemon/skrelp/front.animated.2bpp.lz"
StaryuFrontpic:      INCBIN "gfx/pokemon/staryu/front.animated.2bpp.lz"
HikerPic:            INCBIN "gfx/trainers/hiker.2bpp.lz"
MeowthFrontpic:      INCBIN "gfx/pokemon/meowth/front.animated.2bpp.lz"
Porygon2Frontpic:    INCBIN "gfx/pokemon/porygon2/front.animated.2bpp.lz"
SandygastFrontpic:   INCBIN "gfx/pokemon/sandygast/front.animated.2bpp.lz"
BudewFrontpic:    INCBIN "gfx/pokemon/budew/front.animated.2bpp.lz"
RookideeFrontpic:      INCBIN "gfx/pokemon/rookidee/front.animated.2bpp.lz"
BreloomBackpic:     INCBIN "gfx/pokemon/breloom/back.2bpp.lz"


SECTION "Pics 10", ROMX

MisdreavusFrontpic:  INCBIN "gfx/pokemon/misdreavus/front.animated.2bpp.lz"
HoundourFrontpic:    INCBIN "gfx/pokemon/houndour/front.animated.2bpp.lz"
PetililFrontpic:      INCBIN "gfx/pokemon/petilil/front.animated.2bpp.lz"
CelebiFrontpic:      INCBIN "gfx/pokemon/celebi/front.animated.2bpp.lz"
MediumPic:           INCBIN "gfx/trainers/medium.2bpp.lz"
PinecoFrontpic:      INCBIN "gfx/pokemon/pineco/front.animated.2bpp.lz"
ClauncherFrontpic:      INCBIN "gfx/pokemon/clauncher/front.animated.2bpp.lz"
FisherPic:           INCBIN "gfx/trainers/fisher.2bpp.lz"
CutieflyFrontpic:  INCBIN "gfx/pokemon/cutiefly/front.animated.2bpp.lz"
ShroomishFrontpic:       INCBIN "gfx/pokemon/shroomish/front.animated.2bpp.lz"
CeruledgeBackpic:     INCBIN "gfx/pokemon/ceruledge/back.2bpp.lz"
PokefanmPic:         INCBIN "gfx/trainers/pokefan_m.2bpp.lz"
BoarderPic:          INCBIN "gfx/trainers/boarder.2bpp.lz"
WimpodFrontpic:     INCBIN "gfx/pokemon/wimpod/front.animated.2bpp.lz"
MudkipFrontpic:    INCBIN "gfx/pokemon/mudkip/front.animated.2bpp.lz"
GolurkBackpic:      INCBIN "gfx/pokemon/golurk/back.2bpp.lz"
VaroomFrontpic:     INCBIN "gfx/pokemon/varoom/front.animated.2bpp.lz"
LarvestaFrontpic:     INCBIN "gfx/pokemon/larvesta/front.animated.2bpp.lz"
SpiritombBackpic:    INCBIN "gfx/pokemon/spiritomb/back.2bpp.lz"
AurorusFrontpic:     INCBIN "gfx/pokemon/aurorus/front.animated.2bpp.lz"
SkiploomFrontpic:    INCBIN "gfx/pokemon/skiploom/front.animated.2bpp.lz"
MareepFrontpic:      INCBIN "gfx/pokemon/mareep/front.animated.2bpp.lz"
ChuckPic:            INCBIN "gfx/trainers/chuck.2bpp.lz"
EeveeFrontpic:       INCBIN "gfx/pokemon/eevee/front.animated.2bpp.lz"
VikavoltBackpic:   INCBIN "gfx/pokemon/vikavolt/back.2bpp.lz"
RinringFrontpic:       INCBIN "gfx/pokemon/rinring/front.animated.2bpp.lz"
KimonoGirlPic:       INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
HattereneBackpic:     INCBIN "gfx/pokemon/hatterene/back.2bpp.lz"
KecleonFrontpic:       INCBIN "gfx/pokemon/kecleon/front.animated.2bpp.lz"
HatennaFrontpic:        INCBIN "gfx/pokemon/hatenna/front.animated.2bpp.lz"
CloysterBackpic:     INCBIN "gfx/pokemon/cloyster/back.2bpp.lz"
SwabluFrontpic:    INCBIN "gfx/pokemon/swablu/front.animated.2bpp.lz"
UnownFBackpic:       INCBIN "gfx/pokemon/unown_f/back.2bpp.lz"


SECTION "Pics 11", ROMX

HawluchaBackpic:       INCBIN "gfx/pokemon/hawlucha/back.2bpp.lz"
ClefairyFrontpic:    INCBIN "gfx/pokemon/clefairy/front.animated.2bpp.lz"
SlugmaFrontpic:      INCBIN "gfx/pokemon/slugma/front.animated.2bpp.lz"
OrthwormFrontpic:   INCBIN "gfx/pokemon/orthworm/front.animated.2bpp.lz"
SlowpokeFrontpic:    INCBIN "gfx/pokemon/slowpoke/front.animated.2bpp.lz"
ChinglingFrontpic:    INCBIN "gfx/pokemon/chingling/front.animated.2bpp.lz"
JugglerPic:          INCBIN "gfx/trainers/juggler.2bpp.lz"
MarillFrontpic:      INCBIN "gfx/pokemon/marill/front.animated.2bpp.lz"
GuitaristPic:        INCBIN "gfx/trainers/guitarist.2bpp.lz"
PokefanfPic:         INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
VolcaronaBackpic:     INCBIN "gfx/pokemon/volcarona/back.2bpp.lz"
ClairPic:            INCBIN "gfx/trainers/clair.2bpp.lz"
PokemaniacPic:       INCBIN "gfx/trainers/pokemaniac.2bpp.lz"
SkierPic:            INCBIN "gfx/trainers/skier.2bpp.lz"
PupitarFrontpic:     INCBIN "gfx/pokemon/pupitar/front.animated.2bpp.lz"
BellsproutFrontpic:  INCBIN "gfx/pokemon/bellsprout/front.animated.2bpp.lz"
ShellderFrontpic:    INCBIN "gfx/pokemon/shellder/front.animated.2bpp.lz"
CleffaFrontpic:      INCBIN "gfx/pokemon/cleffa/front.animated.2bpp.lz"
GyaradosBackpic:     INCBIN "gfx/pokemon/gyarados/back.2bpp.lz"
GlimmoraBackpic:    INCBIN "gfx/pokemon/glimmora/back.2bpp.lz"
YanmaBackpic:        INCBIN "gfx/pokemon/yanma/back.2bpp.lz"
PinsirBackpic:       INCBIN "gfx/pokemon/pinsir/back.2bpp.lz"
LassPic:             INCBIN "gfx/trainers/lass.2bpp.lz"
ClefableBackpic:     INCBIN "gfx/pokemon/clefable/back.2bpp.lz"
ChatotFrontpic:       INCBIN "gfx/pokemon/chatot/front.animated.2bpp.lz"
EmpoleonBackpic:   INCBIN "gfx/pokemon/empoleon/back.2bpp.lz"
GibleFrontpic:     INCBIN "gfx/pokemon/gible/front.animated.2bpp.lz"
MagnetonBackpic:     INCBIN "gfx/pokemon/magneton/back.2bpp.lz"
QwilfishFrontpic:    INCBIN "gfx/pokemon/qwilfish/front.animated.2bpp.lz"
Zygarde100Backpic:   INCBIN "gfx/pokemon/zygarde100/back.2bpp.lz"
SlowkingBackpic:     INCBIN "gfx/pokemon/slowking/back.2bpp.lz"
ChimechoBackpic:       INCBIN "gfx/pokemon/chimecho/back.2bpp.lz"
CelebiBackpic:       INCBIN "gfx/pokemon/celebi/back.2bpp.lz"
ClauncherBackpic:       INCBIN "gfx/pokemon/clauncher/back.2bpp.lz"
BugCatcherPic:       INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
TyrantrumBackpic:      INCBIN "gfx/pokemon/tyrantrum/back.2bpp.lz"


SECTION "Pics 12", ROMX

SceptileBackpic:     INCBIN "gfx/pokemon/sceptile/back.2bpp.lz"
WalkingWakeBackpic:      INCBIN "gfx/pokemon/walkingwake/back.2bpp.lz"
SunfloraBackpic:     INCBIN "gfx/pokemon/sunflora/back.2bpp.lz"
TrapinchFrontpic:      INCBIN "gfx/pokemon/trapinch/front.animated.2bpp.lz"
RhydonBackpic:       INCBIN "gfx/pokemon/rhydon/back.2bpp.lz"
LarvitarFrontpic:    INCBIN "gfx/pokemon/larvitar/front.animated.2bpp.lz"
TyranitarBackpic:    INCBIN "gfx/pokemon/tyranitar/back.2bpp.lz"
PalossandBackpic:    INCBIN "gfx/pokemon/palossand/back.2bpp.lz"
AnchorageBackpic:       INCBIN "gfx/pokemon/anchorage/back.2bpp.lz"
TwinsPic:            INCBIN "gfx/trainers/twins.2bpp.lz"
FarfetchDBackpic:    INCBIN "gfx/pokemon/farfetch_d/back.2bpp.lz"
CharcadetBackpic:     INCBIN "gfx/pokemon/charcadet/back.2bpp.lz"
TarountulaBackpic:       INCBIN "gfx/pokemon/tarountula/back.2bpp.lz"
FennekinBackpic:    INCBIN "gfx/pokemon/fennekin/back.2bpp.lz"
DartrixBackpic:      INCBIN "gfx/pokemon/dartrix/back.2bpp.lz"
GavillainFrontpic:      INCBIN "gfx/pokemon/gavillain/front.animated.2bpp.lz"
DarmanitanBackpic:     INCBIN "gfx/pokemon/darmanitan/back.2bpp.lz"
ChatotBackpic:        INCBIN "gfx/pokemon/chatot/back.2bpp.lz"
HoppipFrontpic:      INCBIN "gfx/pokemon/hoppip/front.animated.2bpp.lz"
PetililBackpic:       INCBIN "gfx/pokemon/petilil/back.2bpp.lz"
GalvantulaBackpic:       INCBIN "gfx/pokemon/galvantula/back.2bpp.lz"
MalamarBackpic:        INCBIN "gfx/pokemon/malamar/back.2bpp.lz"
BraixenBackpic:      INCBIN "gfx/pokemon/braixen/back.2bpp.lz"
PrinplupBackpic:     INCBIN "gfx/pokemon/prinplup/back.2bpp.lz"
SandygastBackpic:    INCBIN "gfx/pokemon/sandygast/back.2bpp.lz"
SailorPic:           INCBIN "gfx/trainers/sailor.2bpp.lz"
BeautyPic:           INCBIN "gfx/trainers/beauty.2bpp.lz"
ShellderBackpic:     INCBIN "gfx/pokemon/shellder/back.2bpp.lz"
RinringBackpic:        INCBIN "gfx/pokemon/rinring/back.2bpp.lz"
GruntmPic:           INCBIN "gfx/trainers/grunt_m.2bpp.lz"
CactriBackpic:        INCBIN "gfx/pokemon/cactri/back.2bpp.lz"
MagcargoBackpic:     INCBIN "gfx/pokemon/magcargo/back.2bpp.lz"
ArcheopsBackpic:     INCBIN "gfx/pokemon/archeops/back.2bpp.lz"
ScolipedeBackpic:     INCBIN "gfx/pokemon/scolipede/back.2bpp.lz"
MimikyuBackpic:     INCBIN "gfx/pokemon/mimikyu/back.2bpp.lz"
FlareonBackpic:      INCBIN "gfx/pokemon/flareon/back.2bpp.lz"
GrotessBackpic:      INCBIN "gfx/pokemon/grotess/back.2bpp.lz"
TreeckoFrontpic:   INCBIN "gfx/pokemon/treecko/front.animated.2bpp.lz"
StarmieBackpic:      INCBIN "gfx/pokemon/starmie/back.2bpp.lz"


SECTION "Pics 13", ROMX

TirtougaBackpic:      INCBIN "gfx/pokemon/tirtouga/back.2bpp.lz"
RookideeBackpic:       INCBIN "gfx/pokemon/rookidee/back.2bpp.lz"
ScientistPic:        INCBIN "gfx/trainers/scientist.2bpp.lz"
QwilfishBackpic:     INCBIN "gfx/pokemon/qwilfish/back.2bpp.lz"
WarwolfBackpic:       INCBIN "gfx/pokemon/warwolf/back.2bpp.lz"
DelphoxBackpic:   INCBIN "gfx/pokemon/delphox/back.2bpp.lz"
CombuskenBackpic:   INCBIN "gfx/pokemon/combusken/back.2bpp.lz"
RoseradeBackpic:    INCBIN "gfx/pokemon/roserade/back.2bpp.lz"
PichuFrontpic:       INCBIN "gfx/pokemon/pichu/front.animated.2bpp.lz"
JoltikBackpic:   INCBIN "gfx/pokemon/joltik/back.2bpp.lz"
SpidopsBackpic:       INCBIN "gfx/pokemon/spidops/back.2bpp.lz"
PupitarBackpic:      INCBIN "gfx/pokemon/pupitar/back.2bpp.lz"
HeracrossBackpic:    INCBIN "gfx/pokemon/heracross/back.2bpp.lz"
UnownDFrontpic:      INCBIN "gfx/pokemon/unown_d/front.animated.2bpp.lz"
PangshiBackpic:      INCBIN "gfx/pokemon/pangshi/back.2bpp.lz"
StuffulBackpic:      INCBIN "gfx/pokemon/stufful/back.2bpp.lz"
PersianBackpic:      INCBIN "gfx/pokemon/persian/back.2bpp.lz"
LtSurgePic:          INCBIN "gfx/trainers/lt_surge.2bpp.lz"
TeacherPic:          INCBIN "gfx/trainers/teacher.2bpp.lz"
EggPic:              INCBIN "gfx/pokemon/egg/front.animated.2bpp.lz"
EeveeBackpic:        INCBIN "gfx/pokemon/eevee/back.2bpp.lz"
DarumakaBackpic:       INCBIN "gfx/pokemon/darumaka/back.2bpp.lz"
RemoraidFrontpic:    INCBIN "gfx/pokemon/remoraid/front.animated.2bpp.lz"
SphealFrontpic:     INCBIN "gfx/pokemon/spheal/front.animated.2bpp.lz"
AbsolBackpic:         INCBIN "gfx/pokemon/absol/back.2bpp.lz"
VaroomBackpic:      INCBIN "gfx/pokemon/varoom/back.2bpp.lz"
BirdKeeperPic:       INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
FalknerPic:          INCBIN "gfx/trainers/falkner.2bpp.lz"
KarenPic:            INCBIN "gfx/trainers/karen.2bpp.lz"
RoseliaBackpic:     INCBIN "gfx/pokemon/roselia/back.2bpp.lz"
GorochuBackpic:   INCBIN "gfx/pokemon/gorochu/back.2bpp.lz"
OrthwormBackpic:    INCBIN "gfx/pokemon/orthworm/back.2bpp.lz"
KogaPic:             INCBIN "gfx/trainers/koga.2bpp.lz"
GolettBackpic:      INCBIN "gfx/pokemon/golett/back.2bpp.lz"
RaichuBackpic:       INCBIN "gfx/pokemon/raichu/back.2bpp.lz"
WalreinBackpic:    INCBIN "gfx/pokemon/walrein/back.2bpp.lz"
SwimmermPic:         INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
SunkernFrontpic:     INCBIN "gfx/pokemon/sunkern/front.animated.2bpp.lz"
ArmarogueBackpic:     INCBIN "gfx/pokemon/armarogue/back.2bpp.lz"
MysticalmanPic:      INCBIN "gfx/trainers/mysticalman.2bpp.lz"
CooltrainerfPic:     INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
MorgremFrontpic:   INCBIN "gfx/pokemon/morgrem/front.animated.2bpp.lz"


SECTION "Pics 14", ROMX

FlaaffyBackpic:      INCBIN "gfx/pokemon/flaaffy/back.2bpp.lz"
SentretFrontpic:     INCBIN "gfx/pokemon/sentret/front.animated.2bpp.lz"
TinkatinkBackpic:      INCBIN "gfx/pokemon/tinkatink/back.2bpp.lz"
BugsyPic:            INCBIN "gfx/trainers/bugsy.2bpp.lz"
MarowakBackpic:      INCBIN "gfx/pokemon/marowak/back.2bpp.lz"
AronBackpic:      INCBIN "gfx/pokemon/aron/back.2bpp.lz"
ScytherBackpic:      INCBIN "gfx/pokemon/scyther/back.2bpp.lz"
SharpoonBackpic:    INCBIN "gfx/pokemon/sharpoon/back.2bpp.lz"
LatiosBackpic:   INCBIN "gfx/pokemon/latios/back.2bpp.lz"
JumpluffBackpic:     INCBIN "gfx/pokemon/jumpluff/back.2bpp.lz"
CooltrainermPic:     INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
SwampertBackpic:    INCBIN "gfx/pokemon/swampert/back.2bpp.lz"
MisdreavusBackpic:   INCBIN "gfx/pokemon/misdreavus/back.2bpp.lz"
AronFrontpic:     INCBIN "gfx/pokemon/aron/front.animated.2bpp.lz"
ScizorBackpic:       INCBIN "gfx/pokemon/scizor/back.2bpp.lz"
FlygonBackpic:     INCBIN "gfx/pokemon/flygon/back.2bpp.lz"
SmeargleBackpic:     INCBIN "gfx/pokemon/smeargle/back.2bpp.lz"
BlazikenBackpic:    INCBIN "gfx/pokemon/blaziken/back.2bpp.lz"
HattremBackpic:      INCBIN "gfx/pokemon/hattrem/back.2bpp.lz"
LilligantBackpic:     INCBIN "gfx/pokemon/lilligant/back.2bpp.lz"
FurretBackpic:       INCBIN "gfx/pokemon/furret/back.2bpp.lz"
MarshtompBackpic:    INCBIN "gfx/pokemon/marshtomp/back.2bpp.lz"
GrimmsnarlBackpic:    INCBIN "gfx/pokemon/grimmsnarl/back.2bpp.lz"
LinooneBackpic:     INCBIN "gfx/pokemon/linoone/back.2bpp.lz"
GlimmetBackpic:       INCBIN "gfx/pokemon/glimmet/back.2bpp.lz"
KotoraBackpic:        INCBIN "gfx/pokemon/kotora/back.2bpp.lz"
BurglarPic:          INCBIN "gfx/trainers/burglar.2bpp.lz"
WimpodBackpic:      INCBIN "gfx/pokemon/wimpod/back.2bpp.lz"
PikachuBackpic:      INCBIN "gfx/pokemon/pikachu/back.2bpp.lz"
ArchenFrontpic:      INCBIN "gfx/pokemon/archen/front.animated.2bpp.lz"
MareepBackpic:       INCBIN "gfx/pokemon/mareep/back.2bpp.lz"
RemoraidBackpic:     INCBIN "gfx/pokemon/remoraid/back.2bpp.lz"
DittoFrontpic:       INCBIN "gfx/pokemon/ditto/front.animated.2bpp.lz"
CramorantBackpic:      INCBIN "gfx/pokemon/cramorant/back.2bpp.lz"
CamperPic:           INCBIN "gfx/trainers/camper.2bpp.lz"
WooperFrontpic:      INCBIN "gfx/pokemon/wooper/front.animated.2bpp.lz"
ClefairyBackpic:     INCBIN "gfx/pokemon/clefairy/back.2bpp.lz"
LarvestaBackpic:      INCBIN "gfx/pokemon/larvesta/back.2bpp.lz"
Rival1Pic:           INCBIN "gfx/trainers/rival1.2bpp.lz"
SwinubBackpic:       INCBIN "gfx/pokemon/swinub/back.2bpp.lz"


SECTION "Pics 15", ROMX

NecrozmaBackpic:       INCBIN "gfx/pokemon/necrozma/back.2bpp.lz"
PokemonProfPic:      INCBIN "gfx/trainers/oak.2bpp.lz"
CalPic:              INCBIN "gfx/trainers/cal.2bpp.lz"
SwimmerfPic:         INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
OfficerPic:          INCBIN "gfx/trainers/officer.2bpp.lz"
TurbannBackpic:     INCBIN "gfx/pokemon/turbann/back.2bpp.lz"
SabrinaPic:          INCBIN "gfx/trainers/sabrina.2bpp.lz"
MagikarpBackpic:     INCBIN "gfx/pokemon/magikarp/back.2bpp.lz"
KirliaBackpic:      INCBIN "gfx/pokemon/kirlia/back.2bpp.lz"
SneaselBackpic:      INCBIN "gfx/pokemon/sneasel/back.2bpp.lz"
UmbreonBackpic:      INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
YanmegaBackpic:      INCBIN "gfx/pokemon/yanmega/back.2bpp.lz"
GrovyleBackpic:      INCBIN "gfx/pokemon/grovyle/back.2bpp.lz"
SlowbroBackpic:      INCBIN "gfx/pokemon/slowbro/back.2bpp.lz"
PsychicTPic:         INCBIN "gfx/trainers/psychic_t.2bpp.lz"
Zygarde50Backpic:        INCBIN "gfx/pokemon/zygarde50/back.2bpp.lz"
GruntfPic:           INCBIN "gfx/trainers/grunt_f.2bpp.lz"
CorasunFrontpic:      INCBIN "gfx/pokemon/corasun/front.animated.2bpp.lz"
CorviknightBackpic:      INCBIN "gfx/pokemon/corviknight/back.2bpp.lz"
HoOhBackpic:         INCBIN "gfx/pokemon/ho_oh/back.2bpp.lz"
SealeoBackpic:    INCBIN "gfx/pokemon/sealeo/back.2bpp.lz"
JirachiBackpic:          INCBIN "gfx/pokemon/jirachi/back.2bpp.lz"
DedenneBackpic:       INCBIN "gfx/pokemon/dedenne/back.2bpp.lz"
HatennaBackpic:         INCBIN "gfx/pokemon/hatenna/back.2bpp.lz"
TyruntBackpic:   INCBIN "gfx/pokemon/tyrunt/back.2bpp.lz"
WhirlipedeFrontpic:      INCBIN "gfx/pokemon/whirlipede/front.animated.2bpp.lz"
ExcadrillBackpic:      INCBIN "gfx/pokemon/excadrill/back.2bpp.lz"
WeepinbellBackpic:   INCBIN "gfx/pokemon/weepinbell/back.2bpp.lz"
BudewBackpic:     INCBIN "gfx/pokemon/budew/back.2bpp.lz"
LaironBackpic:     INCBIN "gfx/pokemon/lairon/back.2bpp.lz"
KecleonBackpic:        INCBIN "gfx/pokemon/kecleon/back.2bpp.lz"
EspeonBackpic:       INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
VenipedeFrontpic:      INCBIN "gfx/pokemon/venipede/front.animated.2bpp.lz"
PiplupBackpic:     INCBIN "gfx/pokemon/piplup/back.2bpp.lz"
BewearBackpic:     INCBIN "gfx/pokemon/bewear/back.2bpp.lz"
ClawitzerBackpic:      INCBIN "gfx/pokemon/clawitzer/back.2bpp.lz"
GengarBackpic:       INCBIN "gfx/pokemon/gengar/back.2bpp.lz"
ZigzagoonBackpic:      INCBIN "gfx/pokemon/zigzagoon/back.2bpp.lz"
YoungsterPic:        INCBIN "gfx/trainers/youngster.2bpp.lz"
WillPic:             INCBIN "gfx/trainers/will.2bpp.lz"
SchoolboyPic:        INCBIN "gfx/trainers/schoolboy.2bpp.lz"
MagnemiteFrontpic:   INCBIN "gfx/pokemon/magnemite/front.animated.2bpp.lz"
ErikaPic:            INCBIN "gfx/trainers/erika.2bpp.lz"
JaninePic:           INCBIN "gfx/trainers/janine.2bpp.lz"
MagnemiteBackpic:    INCBIN "gfx/pokemon/magnemite/back.2bpp.lz"


SECTION "Pics 16", ROMX

SwabluBackpic:     INCBIN "gfx/pokemon/swablu/back.2bpp.lz"
AltariaBackpic:      INCBIN "gfx/pokemon/altaria/back.2bpp.lz"
MortyPic:            INCBIN "gfx/trainers/morty.2bpp.lz"
SlugmaBackpic:       INCBIN "gfx/pokemon/slugma/back.2bpp.lz"
ArchenBackpic:       INCBIN "gfx/pokemon/archen/back.2bpp.lz"
VictreebelBackpic:   INCBIN "gfx/pokemon/victreebel/back.2bpp.lz"
MeowthBackpic:       INCBIN "gfx/pokemon/meowth/back.2bpp.lz"
PicnickerPic:        INCBIN "gfx/trainers/picnicker.2bpp.lz"
LickitungBackpic:    INCBIN "gfx/pokemon/lickitung/back.2bpp.lz"
SuperNerdPic:        INCBIN "gfx/trainers/super_nerd.2bpp.lz"
HaunterBackpic:      INCBIN "gfx/pokemon/haunter/back.2bpp.lz"
TinkatonBackpic:         INCBIN "gfx/pokemon/tinkaton/back.2bpp.lz"
RedPic:              INCBIN "gfx/trainers/red.2bpp.lz"
Porygon2Backpic:     INCBIN "gfx/pokemon/porygon2/back.2bpp.lz"
JasminePic:          INCBIN "gfx/trainers/jasmine.2bpp.lz"
PinecoBackpic:       INCBIN "gfx/pokemon/pineco/back.2bpp.lz"
CharjabugFrontpic:     INCBIN "gfx/pokemon/charjabug/front.animated.2bpp.lz"
WailmerBackpic:         INCBIN "gfx/pokemon/wailmer/back.2bpp.lz"
QuagsireBackpic:     INCBIN "gfx/pokemon/quagsire/back.2bpp.lz"
WhitneyPic:          INCBIN "gfx/trainers/whitney.2bpp.lz"
JolteonBackpic:      INCBIN "gfx/pokemon/jolteon/back.2bpp.lz"
GrubbinFrontpic:    INCBIN "gfx/pokemon/grubbin/front.animated.2bpp.lz"
HoppipBackpic:       INCBIN "gfx/pokemon/hoppip/back.2bpp.lz"
BluePic:             INCBIN "gfx/trainers/blue.2bpp.lz"
PorygonZBackpic:     INCBIN "gfx/pokemon/porygonz/back.2bpp.lz"
GentlemanPic:        INCBIN "gfx/trainers/gentleman.2bpp.lz"
ExecutivemPic:       INCBIN "gfx/trainers/executive_m.2bpp.lz"
TaillowBackpic:      INCBIN "gfx/pokemon/taillow/back.2bpp.lz"
SunkernBackpic:      INCBIN "gfx/pokemon/sunkern/back.2bpp.lz"
FalinksBackpic:       INCBIN "gfx/pokemon/falinks/back.2bpp.lz"
KurstrawBackpic:        INCBIN "gfx/pokemon/kurstraw/back.2bpp.lz"
GabiteBackpic:    INCBIN "gfx/pokemon/gabite/back.2bpp.lz"
GougingFireBackpic:       INCBIN "gfx/pokemon/gougingfire/back.2bpp.lz"
MamoswineBackpic:      INCBIN "gfx/pokemon/mamoswine/back.2bpp.lz"
AmauraBackpic:     INCBIN "gfx/pokemon/amaura/back.2bpp.lz"
ChanseyBackpic:      INCBIN "gfx/pokemon/chansey/back.2bpp.lz"
SkiploomBackpic:     INCBIN "gfx/pokemon/skiploom/back.2bpp.lz"
Rival2Pic:           INCBIN "gfx/trainers/rival2.2bpp.lz"
UnownWFrontpic:      INCBIN "gfx/pokemon/unown_w/front.animated.2bpp.lz"
TorchicBackpic:   INCBIN "gfx/pokemon/torchic/back.2bpp.lz"
RhyhornBackpic:      INCBIN "gfx/pokemon/rhyhorn/back.2bpp.lz"
UnownCFrontpic:      INCBIN "gfx/pokemon/unown_c/front.animated.2bpp.lz"
MistyPic:            INCBIN "gfx/trainers/misty.2bpp.lz"
BlainePic:           INCBIN "gfx/trainers/blaine.2bpp.lz"
UnownZFrontpic:      INCBIN "gfx/pokemon/unown_z/front.animated.2bpp.lz"
SwinubFrontpic:      INCBIN "gfx/pokemon/swinub/front.animated.2bpp.lz"
LarvitarBackpic:     INCBIN "gfx/pokemon/larvitar/back.2bpp.lz"
PorygonBackpic:      INCBIN "gfx/pokemon/porygon/back.2bpp.lz"
UnownHBackpic:       INCBIN "gfx/pokemon/unown_h/back.2bpp.lz"


SECTION "Pics 17", ROMX

ShroomishBackpic:        INCBIN "gfx/pokemon/shroomish/back.2bpp.lz"
VaporeonBackpic:     INCBIN "gfx/pokemon/vaporeon/back.2bpp.lz"
LilligantHisuiBackpic:    INCBIN "gfx/pokemon/lilligant_h/back.2bpp.lz"
ExecutivefPic:       INCBIN "gfx/trainers/executive_f.2bpp.lz"
TreeckoBackpic:    INCBIN "gfx/pokemon/treecko/back.2bpp.lz"
ChinglingBackpic:     INCBIN "gfx/pokemon/chingling/back.2bpp.lz"
PichuBackpic:        INCBIN "gfx/pokemon/pichu/back.2bpp.lz"
HoundoomBackpic:     INCBIN "gfx/pokemon/houndoom/back.2bpp.lz"
BellsproutBackpic:   INCBIN "gfx/pokemon/bellsprout/back.2bpp.lz"
SkrelpBackpic:       INCBIN "gfx/pokemon/skrelp/back.2bpp.lz"
AurorusBackpic:      INCBIN "gfx/pokemon/aurorus/back.2bpp.lz"
CorvisquireBackpic:    INCBIN "gfx/pokemon/corvisquire/back.2bpp.lz"
StaryuBackpic:       INCBIN "gfx/pokemon/staryu/back.2bpp.lz"
LickikingBackpic:       INCBIN "gfx/pokemon/lickiking/back.2bpp.lz"
GrubbinBackpic:     INCBIN "gfx/pokemon/grubbin/back.2bpp.lz"
ImpidimpFrontpic:     INCBIN "gfx/pokemon/impidimp/front.animated.2bpp.lz"
LugiaBackpic:        INCBIN "gfx/pokemon/lugia/back.2bpp.lz"
PrycePic:            INCBIN "gfx/trainers/pryce.2bpp.lz"
BrockPic:            INCBIN "gfx/trainers/brock.2bpp.lz"
UnownGFrontpic:      INCBIN "gfx/pokemon/unown_g/front.animated.2bpp.lz"
RaitoraBackpic:        INCBIN "gfx/pokemon/raitora/back.2bpp.lz"
PraxeBackpic:     INCBIN "gfx/pokemon/praxe/back.2bpp.lz"
GarchompBackpic:    INCBIN "gfx/pokemon/garchomp/back.2bpp.lz"
LatiasBackpic:    INCBIN "gfx/pokemon/latias/back.2bpp.lz"
TinkatuffFrontpic:        INCBIN "gfx/pokemon/tinkatuff/front.animated.2bpp.lz"
RelicanthBackpic:     INCBIN "gfx/pokemon/relicanth/back.2bpp.lz"
SagePic:             INCBIN "gfx/trainers/sage.2bpp.lz"
WeavileBackpic:    INCBIN "gfx/pokemon/weavile/back.2bpp.lz"
TrapinchBackpic:       INCBIN "gfx/pokemon/trapinch/back.2bpp.lz"
UnownVFrontpic:      INCBIN "gfx/pokemon/unown_v/front.animated.2bpp.lz"
WhirlipedeBackpic:       INCBIN "gfx/pokemon/whirlipede/back.2bpp.lz"
MismagiusBackpic:    INCBIN "gfx/pokemon/mismagius/back.2bpp.lz"
BlisseyBackpic:      INCBIN "gfx/pokemon/blissey/back.2bpp.lz"
AmpharosBackpic:     INCBIN "gfx/pokemon/ampharos/back.2bpp.lz"
MagnezoneBackpic:    INCBIN "gfx/pokemon/magnezone/back.2bpp.lz"
AzumarillBackpic:    INCBIN "gfx/pokemon/azumarill/back.2bpp.lz"
OctilleryBackpic:    INCBIN "gfx/pokemon/octillery/back.2bpp.lz"
UnownSFrontpic:      INCBIN "gfx/pokemon/unown_s/front.animated.2bpp.lz"
SentretBackpic:      INCBIN "gfx/pokemon/sentret/back.2bpp.lz"
UnownOFrontpic:      INCBIN "gfx/pokemon/unown_o/front.animated.2bpp.lz"
UnownTFrontpic:      INCBIN "gfx/pokemon/unown_t/front.animated.2bpp.lz"
DittoBackpic:        INCBIN "gfx/pokemon/ditto/back.2bpp.lz"
VenipedeBackpic:       INCBIN "gfx/pokemon/venipede/back.2bpp.lz"
UnownHFrontpic:      INCBIN "gfx/pokemon/unown_h/front.animated.2bpp.lz"
CleffaBackpic:       INCBIN "gfx/pokemon/cleffa/back.2bpp.lz"
GastlyBackpic:       INCBIN "gfx/pokemon/gastly/back.2bpp.lz"
SwellowBackpic:       INCBIN "gfx/pokemon/swellow/back.2bpp.lz"
MarillBackpic:       INCBIN "gfx/pokemon/marill/back.2bpp.lz"
GibleBackpic:      INCBIN "gfx/pokemon/gible/back.2bpp.lz"
MorgremBackpic:    INCBIN "gfx/pokemon/morgrem/back.2bpp.lz"
CharjabugBackpic:      INCBIN "gfx/pokemon/charjabug/back.2bpp.lz"
CutieflyBackpic:   INCBIN "gfx/pokemon/cutiefly/back.2bpp.lz"
GavillainBackpic:       INCBIN "gfx/pokemon/gavillain/back.2bpp.lz"
UnownDBackpic:       INCBIN "gfx/pokemon/unown_d/back.2bpp.lz"
UnownEFrontpic:      INCBIN "gfx/pokemon/unown_e/front.animated.2bpp.lz"

SECTION "Pics 18", ROMX

RaltsBackpic:     INCBIN "gfx/pokemon/ralts/back.2bpp.lz"
Zygarde10Backpic:       INCBIN "gfx/pokemon/zygarde10/back.2bpp.lz"
UnownKFrontpic:      INCBIN "gfx/pokemon/unown_k/front.animated.2bpp.lz"
HoundourBackpic:     INCBIN "gfx/pokemon/houndour/back.2bpp.lz"
SphealBackpic:      INCBIN "gfx/pokemon/spheal/back.2bpp.lz"
MudkipBackpic:     INCBIN "gfx/pokemon/mudkip/back.2bpp.lz"
NumpuffBackpic:      INCBIN "gfx/pokemon/numpuff/back.2bpp.lz"
WailordBackpic:      INCBIN "gfx/pokemon/wailord/back.2bpp.lz"
UnownBFrontpic:      INCBIN "gfx/pokemon/unown_b/front.animated.2bpp.lz"
SlowpokeBackpic:     INCBIN "gfx/pokemon/slowpoke/back.2bpp.lz"
WolfmanBackpic:    INCBIN "gfx/pokemon/wolfman/back.2bpp.lz"
VibravaBackpic:      INCBIN "gfx/pokemon/vibrava/back.2bpp.lz"
WooperBackpic:       INCBIN "gfx/pokemon/wooper/back.2bpp.lz"
LuxwanBackpic:       INCBIN "gfx/pokemon/luxwan/back.2bpp.lz"
UnownXFrontpic:      INCBIN "gfx/pokemon/unown_x/front.animated.2bpp.lz"
UnownNFrontpic:      INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
TangelaBackpic:      INCBIN "gfx/pokemon/tangela/back.2bpp.lz"
ImpidimpBackpic:      INCBIN "gfx/pokemon/impidimp/back.2bpp.lz"
UnownJFrontpic:      INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
MantineBackpic:      INCBIN "gfx/pokemon/mantine/back.2bpp.lz"
UnownLFrontpic:      INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
PiloswineBackpic:    INCBIN "gfx/pokemon/piloswine/back.2bpp.lz"
UnownMFrontpic:      INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
UnownFFrontpic:      INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
TinkatuffBackpic:         INCBIN "gfx/pokemon/tinkatuff/back.2bpp.lz"
UnownAFrontpic:      INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
AggronBackpic:        INCBIN "gfx/pokemon/aggron/back.2bpp.lz"
UnownUFrontpic:      INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
DrilburBackpic:      INCBIN "gfx/pokemon/drilbur/back.2bpp.lz"
UnownQFrontpic:      INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
UnownPFrontpic:      INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
UnownCBackpic:       INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
SwavybellBackpic:         INCBIN "gfx/pokemon/swavybell/back.2bpp.lz"
BellerunBackpic:       INCBIN "gfx/pokemon/bellerun/back.2bpp.lz"
UnownYFrontpic:      INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
UnownGBackpic:       INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
UnownIFrontpic:      INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
UnownVBackpic:       INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
ForretressBackpic:   INCBIN "gfx/pokemon/forretress/back.2bpp.lz"
UnownSBackpic:       INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
UnownRFrontpic:      INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"
UnownEBackpic:       INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
UnownJBackpic:       INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
UnownBBackpic:       INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
UnownOBackpic:       INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
UnownZBackpic:       INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
UnownWBackpic:       INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
UnownNBackpic:       INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
UnownABackpic:       INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
UnownMBackpic:       INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
UnownKBackpic:       INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
UnownTBackpic:       INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
UnownXBackpic:       INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
UnownLBackpic:       INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
UnownUBackpic:       INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
UnownQBackpic:       INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
UnownYBackpic:       INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
UnownPBackpic:       INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
UnownIBackpic:       INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
UnownRBackpic:       INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"


SECTION "Pics 19", ROMX

LickitungFrontpic:   INCBIN "gfx/pokemon/lickitung/front.animated.2bpp.lz"
CramorantFrontpic:     INCBIN "gfx/pokemon/cramorant/front.animated.2bpp.lz"
CombuskenFrontpic:  INCBIN "gfx/pokemon/combusken/front.animated.2bpp.lz"
HattremFrontpic:     INCBIN "gfx/pokemon/hattrem/front.animated.2bpp.lz"
SpiritombFrontpic:   INCBIN "gfx/pokemon/spiritomb/front.animated.2bpp.lz"
RowletBackpic:    INCBIN "gfx/pokemon/rowlet/back.2bpp.lz"
DecidueyeBackpic:     INCBIN "gfx/pokemon/decidueye/back.2bpp.lz"
RagingBoltBackpic:     INCBIN "gfx/pokemon/ragingbolt/back.2bpp.lz"
BlacephalonFrontpic:     INCBIN "gfx/pokemon/blacephalon/front.animated.2bpp.lz"
StakatakaBackpic:    INCBIN "gfx/pokemon/stakataka/back.2bpp.lz"
RaltsFrontpic:    INCBIN "gfx/pokemon/ralts/front.animated.2bpp.lz"
GalladeFrontpic:      INCBIN "gfx/pokemon/gallade/front.animated.2bpp.lz"
GalladeBackpic:       INCBIN "gfx/pokemon/gallade/back.2bpp.lz"
GardevoirBackpic:       INCBIN "gfx/pokemon/gardevoir/back.2bpp.lz"
CuboneBackpic:       INCBIN "gfx/pokemon/cubone/back.2bpp.lz"
AggronFrontpic:       INCBIN "gfx/pokemon/aggron/front.animated.2bpp.lz"
ArcheopsFrontpic:    INCBIN "gfx/pokemon/archeops/front.animated.2bpp.lz"
DragalgeBackpic:          INCBIN "gfx/pokemon/dragalge/back.2bpp.lz"
DrilburFrontpic:     INCBIN "gfx/pokemon/drilbur/front.animated.2bpp.lz"
GolisopodBackpic:      INCBIN "gfx/pokemon/golisopod/back.2bpp.lz"
RevavroomBackpic:      INCBIN "gfx/pokemon/revavroom/back.2bpp.lz"

; Sections "Pics 20" to "Pics 24" are not used for any graphics,
; but entries for their banks exist in FixPicBank (see engine/gfx/load_pics.asm).

SECTION "Pics 20", ROMX
PhantumpFrontpic:   INCBIN "gfx/pokemon/phantump/front.animated.2bpp.lz"
RhyperiorFrontpic:   INCBIN "gfx/pokemon/rhyperior/front.animated.2bpp.lz"
YanmegaFrontpic:     INCBIN "gfx/pokemon/yanmega/front.animated.2bpp.lz"
PorygonZFrontpic:    INCBIN "gfx/pokemon/porygonz/front.animated.2bpp.lz"
SwavybellFrontpic:        INCBIN "gfx/pokemon/swavybell/front.animated.2bpp.lz"
MismagiusFrontpic:   INCBIN "gfx/pokemon/mismagius/front.animated.2bpp.lz"
TurbannFrontpic:    INCBIN "gfx/pokemon/turbann/front.animated.2bpp.lz"
InkayBackpic:      INCBIN "gfx/pokemon/inkay/back.2bpp.lz"
RibombeeBackpic:   INCBIN "gfx/pokemon/ribombee/back.2bpp.lz"
CorasunBackpic:       INCBIN "gfx/pokemon/corasun/back.2bpp.lz"

SECTION "Pics 21", ROMX
NumpuffFrontpic:     INCBIN "gfx/pokemon/numpuff/front.animated.2bpp.lz"
MettoBackpic:    INCBIN "gfx/pokemon/metto/back.2bpp.lz"
PhantumpBackpic:    INCBIN "gfx/pokemon/phantump/back.2bpp.lz"
WeavileFrontpic:   INCBIN "gfx/pokemon/weavile/front.animated.2bpp.lz"

SECTION "Pics 22", ROMX
TangorestBackpic:      INCBIN "gfx/pokemon/tangorest/back.2bpp.lz"
MagnezoneFrontpic:   INCBIN "gfx/pokemon/magnezone/front.animated.2bpp.lz"
RhyperiorBackpic:    INCBIN "gfx/pokemon/rhyperior/back.2bpp.lz"
BlacephalonBackpic:      INCBIN "gfx/pokemon/blacephalon/back.2bpp.lz"
TrevenantFrontpic:    INCBIN "gfx/pokemon/trevenant/front.animated.2bpp.lz"
TrevenantBackpic:     INCBIN "gfx/pokemon/trevenant/back.2bpp.lz"
LilligantHisuiFrontpic:   INCBIN "gfx/pokemon/lilligant_h/front.animated.2bpp.lz"
TirtougaFrontpic:     INCBIN "gfx/pokemon/tirtouga/front.animated.2bpp.lz"
SylveonFrontpic:     INCBIN "gfx/pokemon/sylveon/front.animated.2bpp.lz"
SlitherWingFrontpic:     INCBIN "gfx/pokemon/slitherwing/front.animated.2bpp.lz"
SylveonBackpic:     INCBIN "gfx/pokemon/sylveon/back.2bpp.lz"
SlitherWingBackpic:     INCBIN "gfx/pokemon/slitherwing/back.2bpp.lz"

SECTION "Pics 23", ROMX
VibravaFrontpic:     INCBIN "gfx/pokemon/vibrava/front.animated.2bpp.lz"
PinsirFrontpic:      INCBIN "gfx/pokemon/pinsir/front.animated.2bpp.lz"

SECTION "Pics 24", ROMX